"use client";
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {landingPathForRole,normalizeAuthUser} from "../../../../lib/auth-session";
import Link from "next/link";
type School={id:string;name:string;code:string;slug:string;logo_url:string};
async function readResponse(response:Response){const text=await response.text();if(!text)return {};try{return JSON.parse(text)}catch{return {error:`API returned HTTP ${response.status}`}}}
export default function SchoolLogin(){
 const params=useParams<{slug:string}>(),router=useRouter(),slug=String(params.slug||"");
 const[school,setSchool]=useState<School|null>(null),[loadingSchool,setLoadingSchool]=useState(true),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!slug)return;fetch("/backend/public/schools/"+encodeURIComponent(slug)).then(async r=>{const d=await readResponse(r);if(r.status===410)throw Error("This school account is currently inactive. Please contact the platform administrator.");if(!r.ok)throw Error(d?.error||"School not found");setSchool(d)}).catch(e=>setError(e instanceof Error?e.message:"School not found")).finally(()=>setLoadingSchool(false))},[slug]);
 async function login(e:React.FormEvent){e.preventDefault();if(!school)return;setLoading(true);setError("");try{const r=await fetch("/backend/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,school_slug:school.slug})});const d=await readResponse(r);if(!r.ok)throw Error(d?.error?.message||d?.error||"Invalid email or password.");if(!d.access_token||!d.refresh_token)throw Error("Login response is missing authentication tokens");localStorage.setItem("access_token",d.access_token);localStorage.setItem("refresh_token",d.refresh_token);localStorage.setItem("school_code",school.code);const me=await fetch("/backend/me",{headers:{Authorization:"Bearer "+d.access_token}}),payload=await readResponse(me),user=normalizeAuthUser(payload);if(!me.ok||!user){localStorage.removeItem("access_token");localStorage.removeItem("refresh_token");throw Error(payload?.error?.message||payload?.error||"Unable to load your account after sign-in");}if(user.school_name&&user.school_name!==school.name){localStorage.removeItem("access_token");localStorage.removeItem("refresh_token");throw Error("Your account does not belong to this school.");}router.push(landingPathForRole(user.role))}catch(e){setError(e instanceof Error?e.message:"Invalid email or password.")}finally{setLoading(false)}}
 return <main className="auth-shell"><section className="auth-card auth-card-wide">{loadingSchool&&<div className="tenant-note"><strong>Loading school...</strong><span>Preparing your secure school portal.</span></div>}{!loadingSchool&&school&&<><div className="auth-brand"><img className="auth-logo" src={school.logo_url} alt={school.name+" logo"}/><div><p className="eyebrow">SCHOOL MANAGEMENT PORTAL</p><span className="tenant-badge">{school.code}</span></div></div><h1>{school.name}</h1><p className="muted">Securely sign in to your school workspace.</p><form onSubmit={login} className="form"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@school.com" autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" autoComplete="current-password" required/></label>{error&&<div className="error">{error}</div>}<button disabled={loading}>{loading?"Signing in...":"Sign in to school"}</button></form><div className="auth-footer"><span>Need a new school workspace?</span><Link href="/school-signup">Register your school</Link></div></>}{!loadingSchool&&!school&&<><div className="auth-brand"><img className="auth-logo" src="/stonez-digital-logo.svg" alt="Stonez Digital"/></div><h1>School not found</h1><p className="muted">Check the school login link or contact the platform administrator.</p><div className="auth-footer"><Link href="/">Return to platform login</Link></div></>}</section></main>
}