package authz

const (
 RoleSuperAdmin="super_admin"; RoleSchoolAdmin="school_admin"; RoleTeacher="teacher"; RoleStudent="student"; RoleParent="parent"; RoleAccountant="accountant"; RoleStaff="staff"
)
const (
 PermissionUsersRead="users.read"; PermissionUsersCreate="users.create"; PermissionUsersUpdate="users.update"; PermissionUsersDelete="users.delete"; PermissionUsersActivate="users.activate"; PermissionUsersDeactivate="users.deactivate"; PermissionRolesAssign="roles.assign"; PermissionAuditRead="audit.read"
 PermissionStudentsRead="students.read"; PermissionStudentsCreate="students.create"; PermissionStudentsUpdate="students.update"; PermissionStudentsDelete="students.delete"
 PermissionAcademicRead="academic.read"; PermissionAcademicManage="academic.manage"; PermissionClassesRead="classes.read"; PermissionClassesManage="classes.manage"; PermissionSubjectsRead="subjects.read"; PermissionSubjectsManage="subjects.manage"
 PermissionAssignmentsRead="teacher_assignments.read"; PermissionAssignmentsManage="teacher_assignments.manage"; PermissionEnrollmentRead="enrollment.read"; PermissionEnrollmentManage="enrollment.manage"
 PermissionAttendanceRead="attendance.read"; PermissionAttendanceManage="attendance.manage"; PermissionAssessmentsRead="assessments.read"; PermissionAssessmentsManage="assessments.manage"; PermissionResultsRead="results.read"; PermissionResultsManage="results.manage"
 PermissionFeesRead="fees.read"; PermissionFeesManage="fees.manage"; PermissionInvoicesRead="invoices.read"; PermissionInvoicesManage="invoices.manage"; PermissionPaymentsRead="payments.read"; PermissionPaymentsManage="payments.manage"
 PermissionTimetableRead="timetable.read"; PermissionTimetableManage="timetable.manage"; PermissionParentPortalRead="parent_portal.read"; PermissionParentPortalManage="parent_portal.manage"; PermissionNotificationsRead="notifications.read"; PermissionNotificationsManage="notifications.manage"
)
var rolePermissions=map[string]map[string]bool{
 RoleSuperAdmin:{PermissionUsersRead:true,PermissionUsersCreate:true,PermissionUsersUpdate:true,PermissionUsersDelete:true,PermissionUsersActivate:true,PermissionUsersDeactivate:true,PermissionStudentsRead:true,PermissionStudentsCreate:true,PermissionStudentsUpdate:true,PermissionStudentsDelete:true,PermissionRolesAssign:true,PermissionAuditRead:true,PermissionAcademicRead:true,PermissionAcademicManage:true,PermissionClassesRead:true,PermissionClassesManage:true,PermissionSubjectsRead:true,PermissionSubjectsManage:true,PermissionAssignmentsRead:true,PermissionAssignmentsManage:true,PermissionEnrollmentRead:true,PermissionEnrollmentManage:true,PermissionAttendanceRead:true,PermissionAttendanceManage:true,PermissionAssessmentsRead:true,PermissionAssessmentsManage:true,PermissionResultsRead:true,PermissionResultsManage:true,PermissionFeesRead:true,PermissionFeesManage:true,PermissionInvoicesRead:true,PermissionInvoicesManage:true,PermissionPaymentsRead:true,PermissionPaymentsManage:true,PermissionTimetableRead:true,PermissionTimetableManage:true,PermissionParentPortalRead:true,PermissionParentPortalManage:true,PermissionNotificationsRead:true,PermissionNotificationsManage:true},
 RoleSchoolAdmin:{PermissionUsersRead:true,PermissionUsersCreate:true,PermissionUsersUpdate:true,PermissionUsersActivate:true,PermissionUsersDeactivate:true,PermissionStudentsRead:true,PermissionStudentsCreate:true,PermissionStudentsUpdate:true,PermissionStudentsDelete:true,PermissionAcademicRead:true,PermissionAcademicManage:true,PermissionClassesRead:true,PermissionClassesManage:true,PermissionSubjectsRead:true,PermissionSubjectsManage:true,PermissionAssignmentsRead:true,PermissionAssignmentsManage:true,PermissionEnrollmentRead:true,PermissionEnrollmentManage:true,PermissionAttendanceRead:true,PermissionAttendanceManage:true,PermissionAssessmentsRead:true,PermissionAssessmentsManage:true,PermissionResultsRead:true,PermissionResultsManage:true,PermissionFeesRead:true,PermissionFeesManage:true,PermissionInvoicesRead:true,PermissionInvoicesManage:true,PermissionPaymentsRead:true,PermissionPaymentsManage:true,PermissionTimetableRead:true,PermissionTimetableManage:true,PermissionParentPortalRead:true,PermissionParentPortalManage:true,PermissionNotificationsRead:true,PermissionNotificationsManage:true},
 RoleTeacher:{PermissionNotificationsRead:true,PermissionAcademicRead:true,PermissionClassesRead:true,PermissionSubjectsRead:true,PermissionAssignmentsRead:true,PermissionEnrollmentRead:true,PermissionAttendanceRead:true,PermissionAttendanceManage:true,PermissionAssessmentsRead:true,PermissionAssessmentsManage:true,PermissionResultsRead:true,PermissionResultsManage:true,PermissionTimetableRead:true},
 RoleStudent:{PermissionTimetableRead:true,PermissionNotificationsRead:true}, RoleParent:{PermissionParentPortalRead:true,PermissionNotificationsRead:true}, RoleAccountant:{PermissionFeesRead:true,PermissionFeesManage:true,PermissionInvoicesRead:true,PermissionInvoicesManage:true,PermissionPaymentsRead:true,PermissionPaymentsManage:true,PermissionNotificationsRead:true}, RoleStaff:{PermissionNotificationsRead:true},
}
func IsValidRole(role string)bool{_,ok:=rolePermissions[role];return ok}
func HasPermission(role,permission string)bool{return rolePermissions[role][permission]}
func PermissionsForRole(role string)[]string{p:=rolePermissions[role];r:=make([]string,0,len(p));for k,v:=range p{if v{r=append(r,k)}};return r}
