
package controller
import("errors";"time";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/audit";"github.com/onoja217/users-management-app/internal/httpx";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/service")
type AcademicController struct{service *service.AcademicService}
func NewAcademicController(s *service.AcademicService)*AcademicController{return &AcademicController{s}}
type academicRequest struct{Name string `json:"name" binding:"required,max=100"`;StartDate time.Time `json:"start_date" binding:"required"`;EndDate time.Time `json:"end_date" binding:"required"`;Status string `json:"status" binding:"omitempty,oneof=planned active closed archived"`}
type termRequest struct{Name string `json:"name" binding:"required,oneof=first second third"`;StartDate time.Time `json:"start_date" binding:"required"`;EndDate time.Time `json:"end_date" binding:"required"`;Status string `json:"status" binding:"omitempty,oneof=planned active closed archived"`}
func academicError(c *gin.Context,e error,resource string){switch{case errors.Is(e,service.ErrAcademicSessionNotFound),errors.Is(e,service.ErrTermNotFound),errors.Is(e,service.ErrAcademicParentNotFound):httpx.Error(c,404,"academic_not_found",resource+" not found");case errors.Is(e,service.ErrAcademicDateRange):httpx.Error(c,400,"invalid_academic_dates","invalid academic date range");case errors.Is(e,service.ErrAcademicDuplicate):httpx.Error(c,409,"academic_duplicate","academic record already exists or has an invalid value");case errors.Is(e,service.ErrAcademicOverlap):httpx.Error(c,409,"academic_overlap","academic date range overlaps another record");default:httpx.Error(c,500,"academic_operation_failed","academic operation failed")}}
func(ctrl *AcademicController)ListSessions(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};v,e:=ctrl.service.GetSessions(schoolID);if e!=nil{academicError(c,e,"academic session");return};c.JSON(200,v)}
func(ctrl *AcademicController)GetSession(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_academic_session_id","invalid academic session id");return};v,e:=ctrl.service.GetSession(schoolID,id);if e!=nil{academicError(c,e,"academic session");return};c.JSON(200,v)}
func(ctrl *AcademicController)CreateSession(c *gin.Context){var r academicRequest;if e:=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};schoolID,ok:=requireSchoolID(c);if !ok{return};v,e:=ctrl.service.CreateSession(schoolID,models.AcademicSession{Name:r.Name,StartDate:r.StartDate,EndDate:r.EndDate,Status:r.Status});if e!=nil{academicError(c,e,"academic session");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"academic_session.create","academic_session",&v.ID,nil);c.JSON(201,v)}
func(ctrl *AcademicController)UpdateSession(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_academic_session_id","invalid academic session id");return};var r academicRequest;if e=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};v,e:=ctrl.service.GetSession(schoolID,id);if e!=nil{academicError(c,e,"academic session");return};v.Name=r.Name;v.StartDate=r.StartDate;v.EndDate=r.EndDate;if r.Status!=""{v.Status=r.Status};if e=ctrl.service.UpdateSession(schoolID,v);e!=nil{academicError(c,e,"academic session");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"academic_session.update","academic_session",&v.ID,nil);c.JSON(200,v)}
func(ctrl *AcademicController)DeleteSession(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_academic_session_id","invalid academic session id");return};if e=ctrl.service.DeleteSession(schoolID,id);e!=nil{academicError(c,e,"academic session");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"academic_session.delete","academic_session",&id,nil);c.JSON(200,gin.H{"message":"academic session deleted"})}
func(ctrl *AcademicController)ListTerms(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};sid,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_academic_session_id","invalid academic session id");return};v,e:=ctrl.service.GetTerms(schoolID,sid);if e!=nil{academicError(c,e,"academic session");return};c.JSON(200,v)}
func(ctrl *AcademicController)GetTerm(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_term_id","invalid term id");return};v,e:=ctrl.service.GetTerm(schoolID,id);if e!=nil{academicError(c,e,"term");return};c.JSON(200,v)}
func(ctrl *AcademicController)CreateTerm(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};sid,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_academic_session_id","invalid academic session id");return};var r termRequest;if e=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};v,e:=ctrl.service.CreateTerm(schoolID,models.Term{AcademicSessionID:sid,Name:r.Name,StartDate:r.StartDate,EndDate:r.EndDate,Status:r.Status});if e!=nil{academicError(c,e,"academic term");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"term.create","term",&v.ID,nil);c.JSON(201,v)}
func(ctrl *AcademicController)UpdateTerm(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_term_id","invalid term id");return};var r termRequest;if e=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};v,e:=ctrl.service.GetTerm(schoolID,id);if e!=nil{academicError(c,e,"term");return};v.Name=r.Name;v.StartDate=r.StartDate;v.EndDate=r.EndDate;if r.Status!=""{v.Status=r.Status};if e=ctrl.service.UpdateTerm(schoolID,v);e!=nil{academicError(c,e,"term");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"term.update","term",&v.ID,nil);c.JSON(200,v)}
func(ctrl *AcademicController)DeleteTerm(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_term_id","invalid term id");return};if e=ctrl.service.DeleteTerm(schoolID,id);e!=nil{academicError(c,e,"term");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"term.delete","term",&id,nil);c.JSON(200,gin.H{"message":"term deleted"})}
