package controller

import("errors";"net/http";"time";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/audit";"github.com/onoja217/users-management-app/internal/httpx";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/service")
type AssessmentController struct{service *service.AssessmentService}
func NewAssessmentController(s *service.AssessmentService)*AssessmentController{return &AssessmentController{s}}
type assessmentRequest struct{TeacherAssignmentID uuid.UUID `json:"teacher_assignment_id"`;Title string `json:"title"`;Type string `json:"type"`;MaxScore float64 `json:"max_score"`;Weight float64 `json:"weight"`;Date string `json:"date"`}
func assessmentError(c *gin.Context,e error){switch{case errors.Is(e,service.ErrAssessmentNotFound):httpx.Error(c,404,"assessment_not_found","assessment not found");case errors.Is(e,service.ErrAssessmentAssignmentMissing):httpx.Error(c,404,"assignment_not_found","teacher assignment not found");case errors.Is(e,service.ErrAssessmentDuplicate):httpx.Error(c,409,"assessment_duplicate","assessment already exists for this assignment");case errors.Is(e,service.ErrAssessmentInvalid):httpx.Error(c,400,"invalid_assessment","invalid assessment configuration");default:httpx.Error(c,500,"assessment_operation_failed","assessment operation failed")}}
func(ctrl *AssessmentController)List(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};sessionID,termID,ok:=parseAcademicQuery(c);if !ok{return};v,e:=ctrl.service.List(schoolID,sessionID,termID);if e!=nil{assessmentError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *AssessmentController)Get(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_assessment_id","invalid assessment id");return};v,e:=ctrl.service.Get(schoolID,id);if e!=nil{assessmentError(c,e);return};c.JSON(http.StatusOK,v)}
func parseAssessmentDate(s string)(time.Time,error){return time.Parse("2006-01-02",s)}
func(ctrl *AssessmentController)Create(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};var r assessmentRequest;if e:=c.ShouldBindJSON(&r);e!=nil||r.TeacherAssignmentID==uuid.Nil||r.Title==""||r.Type==""||r.MaxScore<=0||r.Weight<=0||r.Weight>100||r.Date==""{httpx.Error(c,400,"invalid_assessment_request","assignment, title, type, max score, weight and date are required");return};d,e:=parseAssessmentDate(r.Date);if e!=nil{httpx.Error(c,400,"invalid_assessment_date","date must use YYYY-MM-DD format");return};v,e:=ctrl.service.Create(schoolID,models.Assessment{TeacherAssignmentID:r.TeacherAssignmentID,Title:r.Title,Type:r.Type,MaxScore:r.MaxScore,Weight:r.Weight,Date:d});if e!=nil{assessmentError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"assessment.create","assessment",&v.ID,nil);c.JSON(http.StatusCreated,v)}
func(ctrl *AssessmentController)Update(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_assessment_id","invalid assessment id");return};var r assessmentRequest;if e=c.ShouldBindJSON(&r);e!=nil||r.TeacherAssignmentID==uuid.Nil||r.Title==""||r.Type==""||r.MaxScore<=0||r.Weight<=0||r.Weight>100||r.Date==""{httpx.Error(c,400,"invalid_assessment_request","assignment, title, type, max score, weight and date are required");return};d,e:=parseAssessmentDate(r.Date);if e!=nil{httpx.Error(c,400,"invalid_assessment_date","date must use YYYY-MM-DD format");return};v,e:=ctrl.service.Get(schoolID,id);if e!=nil{assessmentError(c,e);return};v.TeacherAssignmentID=r.TeacherAssignmentID;v.Title=r.Title;v.Type=r.Type;v.MaxScore=r.MaxScore;v.Weight=r.Weight;v.Date=d;if e=ctrl.service.Update(schoolID,v);e!=nil{assessmentError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"assessment.update","assessment",&v.ID,nil);c.JSON(http.StatusOK,v)}
func(ctrl *AssessmentController)Delete(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_assessment_id","invalid assessment id");return};if e=ctrl.service.Delete(schoolID,id);e!=nil{assessmentError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"assessment.delete","assessment",&id,nil);c.JSON(http.StatusOK,gin.H{"message":"assessment deleted"})}

func(ctrl *AssessmentController) TeacherList(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};tid,e:=uuid.Parse(c.GetString("user_id"));if e!=nil{httpx.Error(c,401,"invalid_user","invalid authenticated user");return};sessionID,termID,ok:=parseAcademicQuery(c);if !ok{return};v,e:=ctrl.service.ListForTeacher(schoolID,tid,sessionID,termID);if e!=nil{assessmentError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *AssessmentController) TeacherCreate(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};tid,e:=uuid.Parse(c.GetString("user_id"));if e!=nil{httpx.Error(c,401,"invalid_user","invalid authenticated user");return};var r assessmentRequest;if e=c.ShouldBindJSON(&r);e!=nil||r.TeacherAssignmentID==uuid.Nil||r.Title==""||r.Type==""||r.MaxScore<=0||r.Weight<=0||r.Weight>100||r.Date==""{httpx.Error(c,400,"invalid_assessment_request","assignment, title, type, max score, weight and date are required");return};d,e:=parseAssessmentDate(r.Date);if e!=nil{httpx.Error(c,400,"invalid_assessment_date","date must use YYYY-MM-DD format");return};v,e:=ctrl.service.TeacherCreate(schoolID,tid,models.Assessment{TeacherAssignmentID:r.TeacherAssignmentID,Title:r.Title,Type:r.Type,MaxScore:r.MaxScore,Weight:r.Weight,Date:d});if e!=nil{assessmentError(c,e);return};c.JSON(http.StatusCreated,v)}
