package controller
import("errors";"net/http";"time";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/audit";"github.com/onoja217/users-management-app/internal/httpx";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/service")
type AssessmentController struct{service *service.AssessmentService}
func NewAssessmentController(s *service.AssessmentService)*AssessmentController{return &AssessmentController{s}}
type assessmentRequest struct{TeacherAssignmentID uuid.UUID `json:"teacher_assignment_id" binding:"required"`;Title string `json:"title" binding:"required,max=150"`;Type string `json:"type" binding:"required,max=30"`;MaxScore float64 `json:"max_score" binding:"required"`;Weight float64 `json:"weight" binding:"required"`;AssessmentDate string `json:"assessment_date" binding:"required"`}
func assessmentError(c *gin.Context,e error){switch{case errors.Is(e,service.ErrAssessmentNotFound):httpx.Error(c,404,"assessment_not_found","assessment not found");case errors.Is(e,service.ErrAssessmentInvalid):httpx.Error(c,400,"invalid_assessment","invalid assessment configuration");default:httpx.Error(c,500,"assessment_operation_failed","assessment operation failed")}}
func(ctrl *AssessmentController)List(c *gin.Context){v,e:=ctrl.service.List();if e!=nil{assessmentError(c,e);return};c.JSON(200,v)}
func(ctrl *AssessmentController)Get(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_assessment_id","invalid assessment id");return};v,e:=ctrl.service.Get(id);if e!=nil{assessmentError(c,e);return};c.JSON(200,v)}
func(ctrl *AssessmentController)save(c *gin.Context,update bool){var r assessmentRequest;if e:=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};d,e:=time.Parse(time.RFC3339,r.AssessmentDate);if e!=nil{d,e=time.Parse("2006-01-02",r.AssessmentDate)};if e!=nil{httpx.Error(c,400,"invalid_assessment_date","assessment_date must be RFC3339 or YYYY-MM-DD");return};v:=models.Assessment{TeacherAssignmentID:r.TeacherAssignmentID,Title:r.Title,Type:r.Type,MaxScore:r.MaxScore,Weight:r.Weight,AssessmentDate:d};if update{id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_assessment_id","invalid assessment id");return};v.ID=id;if e=ctrl.service.Update(v);e!=nil{assessmentError(c,e);return}}else{v,e=ctrl.service.Create(v);if e!=nil{assessmentError(c,e);return}};actor,_:=uuid.Parse(c.GetString("user_id"));action:="assessment.create";if update{action="assessment.update"};_=audit.Record(ctrl.service.DB(),c,&actor,action,"assessment",&v.ID,nil);if update{c.JSON(200,v)}else{c.JSON(http.StatusCreated,v)}}
func(ctrl *AssessmentController)Create(c *gin.Context){ctrl.save(c,false)}
func(ctrl *AssessmentController)Update(c *gin.Context){ctrl.save(c,true)}
func(ctrl *AssessmentController)Delete(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_assessment_id","invalid assessment id");return};if e=ctrl.service.Delete(id);e!=nil{assessmentError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"assessment.delete","assessment",&id,nil);c.JSON(200,gin.H{"message":"assessment deleted"})}