package controller
import("errors";"net/http";"time";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/audit";"github.com/onoja217/users-management-app/internal/httpx";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/service")
type AttendanceController struct{service *service.AttendanceService}
func NewAttendanceController(s *service.AttendanceService)*AttendanceController{return &AttendanceController{s}}
type attendanceRequest struct{EnrollmentID uuid.UUID `json:"enrollment_id" binding:"required"`;Date string `json:"date" binding:"required"`;Status string `json:"status" binding:"required"`;Note string `json:"note" binding:"max=255"`}
func attendanceError(c *gin.Context,e error){switch{case errors.Is(e,service.ErrAttendanceNotFound):httpx.Error(c,404,"attendance_not_found","attendance not found");case errors.Is(e,service.ErrAttendanceDuplicate):httpx.Error(c,409,"attendance_duplicate","attendance already recorded for this date");case errors.Is(e,service.ErrAttendanceInvalid):httpx.Error(c,400,"invalid_attendance","invalid enrollment, date or attendance status");default:httpx.Error(c,500,"attendance_operation_failed","attendance operation failed")}}
func(ctrl *AttendanceController)List(c *gin.Context){v,e:=ctrl.service.List();if e!=nil{attendanceError(c,e);return};c.JSON(200,v)}
func(ctrl *AttendanceController)Get(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_attendance_id","invalid attendance id");return};v,e:=ctrl.service.Get(id);if e!=nil{attendanceError(c,e);return};c.JSON(200,v)}
func(ctrl *AttendanceController)save(c *gin.Context,update bool){var r attendanceRequest;if e:=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};d,e:=time.Parse("2006-01-02",r.Date);if e!=nil{httpx.Error(c,400,"invalid_attendance_date","date must use YYYY-MM-DD");return};v:=models.Attendance{EnrollmentID:r.EnrollmentID,Date:d,Status:r.Status,Note:r.Note};if update{id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_attendance_id","invalid attendance id");return};v.ID=id;if e=ctrl.service.Update(v);e!=nil{attendanceError(c,e);return}}else{v,e=ctrl.service.Create(v);if e!=nil{attendanceError(c,e);return}};actor,_:=uuid.Parse(c.GetString("user_id"));action:="attendance.create";if update{action="attendance.update"};_=audit.Record(ctrl.service.DB(),c,&actor,action,"attendance",&v.ID,nil);if update{c.JSON(200,v)}else{c.JSON(http.StatusCreated,v)}}
func(ctrl *AttendanceController)Create(c *gin.Context){ctrl.save(c,false)}
func(ctrl *AttendanceController)Update(c *gin.Context){ctrl.save(c,true)}
func(ctrl *AttendanceController)Delete(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_attendance_id","invalid attendance id");return};if e=ctrl.service.Delete(id);e!=nil{attendanceError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"attendance.delete","attendance",&id,nil);c.JSON(200,gin.H{"message":"attendance deleted"})}