package controller
import("errors";"net/http";"time";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/audit";"github.com/onoja217/users-management-app/internal/httpx";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/service")
type AttendanceController struct{service *service.AttendanceService}
func NewAttendanceController(s *service.AttendanceService)*AttendanceController{return &AttendanceController{s}}
func parseAttendanceDate(v string)(time.Time,error){return time.Parse("2006-01-02",v)}
type attendanceRequest struct{EnrollmentID uuid.UUID `json:"enrollment_id"`;TermID uuid.UUID `json:"term_id"`;Date string `json:"date"`;Status string `json:"status"`;Note string `json:"note"`}
func attendanceError(c *gin.Context,e error){switch{case errors.Is(e,service.ErrAttendanceNotFound):httpx.Error(c,404,"attendance_not_found","attendance record not found");case errors.Is(e,service.ErrAttendanceDuplicate):httpx.Error(c,409,"attendance_duplicate","attendance already recorded for this enrollment on this date");case errors.Is(e,service.ErrAttendanceEnrollmentMissing):httpx.Error(c,404,"enrollment_not_found","active enrollment not found");case errors.Is(e,service.ErrAttendanceTermMissing):httpx.Error(c,404,"term_not_found","term not found");case errors.Is(e,service.ErrAttendanceTermMismatch):httpx.Error(c,400,"term_session_mismatch","term does not belong to enrollment academic session");case errors.Is(e,service.ErrAttendanceInvalidStatus):httpx.Error(c,400,"invalid_attendance_status","invalid attendance status");default:httpx.Error(c,500,"attendance_operation_failed","attendance operation failed")}}
func(ctrl *AttendanceController)List(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};sessionID,termID,ok:=parseAcademicQuery(c);if !ok{return};v,e:=ctrl.service.List(schoolID,sessionID,termID);if e!=nil{attendanceError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *AttendanceController)Get(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_attendance_id","invalid attendance id");return};v,e:=ctrl.service.Get(schoolID,id);if e!=nil{attendanceError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *AttendanceController)Create(c *gin.Context){var r attendanceRequest;if e:=c.ShouldBindJSON(&r);e!=nil||r.EnrollmentID==uuid.Nil||r.TermID==uuid.Nil||r.Date==""||r.Status==""{httpx.Error(c,400,"invalid_attendance_request","enrollment, term, date and status are required");return};d,e:=parseAttendanceDate(r.Date);if e!=nil{httpx.Error(c,400,"invalid_attendance_date","date must use YYYY-MM-DD format");return};schoolID,ok:=requireSchoolID(c);if !ok{return};v,e:=ctrl.service.Create(schoolID,models.AttendanceRecord{EnrollmentID:r.EnrollmentID,TermID:r.TermID,Date:d,Status:r.Status,Note:r.Note});if e!=nil{attendanceError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"attendance.create","attendance_record",&v.ID,nil);c.JSON(http.StatusCreated,v)}
func(ctrl *AttendanceController)Update(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_attendance_id","invalid attendance id");return};var r attendanceRequest;if e=c.ShouldBindJSON(&r);e!=nil||r.EnrollmentID==uuid.Nil||r.TermID==uuid.Nil||r.Date==""||r.Status==""{httpx.Error(c,400,"invalid_attendance_request","enrollment, term, date and status are required");return};d,e:=parseAttendanceDate(r.Date);if e!=nil{httpx.Error(c,400,"invalid_attendance_date","date must use YYYY-MM-DD format");return};v,e:=ctrl.service.Get(schoolID,id);if e!=nil{attendanceError(c,e);return};v.EnrollmentID=r.EnrollmentID;v.TermID=r.TermID;v.Date=d;v.Status=r.Status;v.Note=r.Note;if e=ctrl.service.Update(schoolID,v);e!=nil{attendanceError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"attendance.update","attendance_record",&v.ID,nil);c.JSON(http.StatusOK,v)}
func(ctrl *AttendanceController)Delete(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_attendance_id","invalid attendance id");return};if e=ctrl.service.Delete(schoolID,id);e!=nil{attendanceError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"attendance.delete","attendance_record",&id,nil);c.JSON(http.StatusOK,gin.H{"message":"attendance record deleted"})}

func(ctrl *AttendanceController) TeacherList(c *gin.Context){schoolID,ok:=requireSchoolID(c);if !ok{return};tid,e:=uuid.Parse(c.GetString("user_id"));if e!=nil{httpx.Error(c,401,"invalid_user","invalid authenticated user");return};sessionID,termID,ok:=parseAcademicQuery(c);if !ok{return};v,e:=ctrl.service.ListForTeacher(schoolID,tid,sessionID,termID);if e!=nil{attendanceError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *AttendanceController) TeacherCreate(c *gin.Context){var r attendanceRequest;if e:=c.ShouldBindJSON(&r);e!=nil||r.EnrollmentID==uuid.Nil||r.TermID==uuid.Nil||r.Date==""||r.Status==""{httpx.Error(c,400,"invalid_attendance_request","enrollment, term, date and status are required");return};d,e:=parseAttendanceDate(r.Date);if e!=nil{httpx.Error(c,400,"invalid_attendance_date","date must use YYYY-MM-DD format");return};schoolID,ok:=requireSchoolID(c);if !ok{return};tid,e:=uuid.Parse(c.GetString("user_id"));if e!=nil{httpx.Error(c,401,"invalid_user","invalid authenticated user");return};v,e:=ctrl.service.TeacherCreate(schoolID,tid,models.AttendanceRecord{EnrollmentID:r.EnrollmentID,TermID:r.TermID,Date:d,Status:r.Status,Note:r.Note});if e!=nil{attendanceError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"attendance.create","attendance_record",&v.ID,nil);c.JSON(http.StatusCreated,v)}
