package controller

import("net/http";"strings";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/audit";"github.com/onoja217/users-management-app/internal/httpx";"github.com/onoja217/users-management-app/internal/middleware";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/service")

type BulkImportController struct{service *service.BulkImportService}
func NewBulkImportController(s *service.BulkImportService)*BulkImportController{return &BulkImportController{service:s}}
func(ctrl *BulkImportController)Create(c *gin.Context){schoolID,ok:=middleware.SchoolIDFromContext(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};actor,e:=uuid.Parse(c.GetString("user_id"));if e!=nil{httpx.Error(c,401,"invalid_user","invalid authenticated user");return};kind:=strings.ToLower(strings.TrimSpace(c.PostForm("kind")));file,e:=c.FormFile("file");if e!=nil{httpx.Error(c,400,"file_required","CSV or XLSX file is required");return};rows,e:=service.ParseUpload(file);if e!=nil{httpx.Error(c,400,"invalid_import_file",e.Error());return};sendCredentials:=strings.EqualFold(strings.TrimSpace(c.PostForm("send_credentials")),"true");out,e:=ctrl.service.Create(schoolID,actor,kind,file.Filename,sendCredentials,rows);if e!=nil{httpx.Error(c,400,"import_validation_failed",e.Error());return};_=audit.Record(ctrl.service.DB(),c,&actor,"school.bulk_import.preview","bulk_import",&out.Job.ID,map[string]interface{}{"kind":kind,"total":out.Job.Total,"valid":out.Job.Valid});c.JSON(http.StatusCreated,out)}
func(ctrl *BulkImportController)Start(c *gin.Context){schoolID,ok:=middleware.SchoolIDFromContext(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};actor,_:=uuid.Parse(c.GetString("user_id"));id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_import_id","invalid import id");return};if e=ctrl.service.Start(schoolID,actor,id);e!=nil{if strings.Contains(e.Error(),"not pending"){httpx.Error(c,409,"import_not_pending",e.Error());return};httpx.Error(c,404,"import_not_found","import job not found");return};_=audit.Record(ctrl.service.DB(),c,&actor,"school.bulk_import.start","bulk_import",&id,nil);c.JSON(http.StatusAccepted,gin.H{"id":id,"status":models.BulkImportQueued})}
func(ctrl *BulkImportController)List(c *gin.Context){schoolID,ok:=middleware.SchoolIDFromContext(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};v,e:=ctrl.service.List(schoolID);if e!=nil{httpx.Error(c,500,"imports_failed","unable to list imports");return};c.JSON(http.StatusOK,gin.H{"imports":v})}
func(ctrl *BulkImportController)Get(c *gin.Context){schoolID,ok:=middleware.SchoolIDFromContext(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_import_id","invalid import id");return};v,e:=ctrl.service.Get(schoolID,id);if e!=nil{httpx.Error(c,404,"import_not_found","import job not found");return};c.JSON(http.StatusOK,v)}
