package controller

import ("errors";"net/http";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/audit";"github.com/onoja217/users-management-app/internal/httpx";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/service")

type ClassController struct{service *service.ClassService}
func NewClassController(s *service.ClassService)*ClassController{return &ClassController{s}}
type classRequest struct{Name string `json:"name" binding:"required,max=100"`;Level int `json:"level" binding:"min=0"`}
type sectionRequest struct{Name string `json:"name" binding:"required,max=50"`}
func classError(c *gin.Context,e error,resource string){switch{case errors.Is(e,service.ErrClassNotFound),errors.Is(e,service.ErrSectionNotFound),errors.Is(e,service.ErrClassNotFound):httpx.Error(c,404,"academic_resource_not_found",resource+" not found");case errors.Is(e,service.ErrClassDuplicate),errors.Is(e,service.ErrSectionDuplicate):httpx.Error(c,409,"academic_duplicate",resource+" already exists");case errors.Is(e,service.ErrClassInvalidLevel):httpx.Error(c,400,"invalid_class_level","class level must be zero or greater");default:httpx.Error(c,500,"academic_operation_failed","academic operation failed")}}
func(ctrl *ClassController)ListClasses(c *gin.Context){v,e:=ctrl.service.ListClasses();if e!=nil{classError(c,e,"class");return};c.JSON(200,v)}
func(ctrl *ClassController)GetClass(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_class_id","invalid class id");return};v,e:=ctrl.service.GetClass(id);if e!=nil{classError(c,e,"class");return};c.JSON(200,v)}
func(ctrl *ClassController)CreateClass(c *gin.Context){var r classRequest;if e:=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};v,e:=ctrl.service.CreateClass(models.SchoolClass{Name:r.Name,Level:r.Level});if e!=nil{classError(c,e,"class");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"class.create","class",&v.ID,nil);c.JSON(http.StatusCreated,v)}
func(ctrl *ClassController)UpdateClass(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_class_id","invalid class id");return};var r classRequest;if e=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};v,e:=ctrl.service.GetClass(id);if e!=nil{classError(c,e,"class");return};v.Name=r.Name;v.Level=r.Level;if e=ctrl.service.UpdateClass(v);e!=nil{classError(c,e,"class");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"class.update","class",&v.ID,nil);c.JSON(200,v)}
func(ctrl *ClassController)DeleteClass(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_class_id","invalid class id");return};if e=ctrl.service.DeleteClass(id);e!=nil{classError(c,e,"class");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"class.delete","class",&id,nil);c.JSON(200,gin.H{"message":"class deleted"})}
func(ctrl *ClassController)ListSections(c *gin.Context){id,e:=uuid.Parse(c.Param("classId"));if e!=nil{httpx.Error(c,400,"invalid_class_id","invalid class id");return};v,e:=ctrl.service.ListSections(id);if e!=nil{classError(c,e,"class");return};c.JSON(200,v)}
func(ctrl *ClassController)CreateSection(c *gin.Context){id,e:=uuid.Parse(c.Param("classId"));if e!=nil{httpx.Error(c,400,"invalid_class_id","invalid class id");return};var r sectionRequest;if e=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};v,e:=ctrl.service.CreateSection(models.Section{ClassID:id,Name:r.Name});if e!=nil{classError(c,e,"section");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"section.create","section",&v.ID,nil);c.JSON(http.StatusCreated,v)}
func(ctrl *ClassController)GetSection(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_section_id","invalid section id");return};v,e:=ctrl.service.GetSection(id);if e!=nil{classError(c,e,"section");return};c.JSON(200,v)}
func(ctrl *ClassController)UpdateSection(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_section_id","invalid section id");return};var r sectionRequest;if e=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};v,e:=ctrl.service.GetSection(id);if e!=nil{classError(c,e,"section");return};v.Name=r.Name;if e=ctrl.service.UpdateSection(v);e!=nil{classError(c,e,"section");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"section.update","section",&v.ID,nil);c.JSON(200,v)}
func(ctrl *ClassController)DeleteSection(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_section_id","invalid section id");return};if e=ctrl.service.DeleteSection(id);e!=nil{classError(c,e,"section");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"section.delete","section",&id,nil);c.JSON(200,gin.H{"message":"section deleted"})}
