package controller
import("errors";"net/http";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/audit";"github.com/onoja217/users-management-app/internal/httpx";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/service")
type EnrollmentController struct{service *service.EnrollmentService}
func NewEnrollmentController(s *service.EnrollmentService)*EnrollmentController{return &EnrollmentController{s}}
type enrollmentRequest struct{StudentID uuid.UUID `json:"student_id" binding:"required"`;AcademicSessionID uuid.UUID `json:"academic_session_id" binding:"required"`;ClassID uuid.UUID `json:"class_id" binding:"required"`;SectionID uuid.UUID `json:"section_id" binding:"required"`;Status string `json:"status"`}
func enrollmentError(c *gin.Context,e error){switch{case errors.Is(e,service.ErrEnrollmentNotFound):httpx.Error(c,404,"enrollment_not_found","enrollment not found");case errors.Is(e,service.ErrEnrollmentDuplicate):httpx.Error(c,409,"enrollment_duplicate","student is already enrolled in this academic session");case errors.Is(e,service.ErrEnrollmentInvalid):httpx.Error(c,400,"invalid_enrollment","student, session, class, section or status is invalid");default:httpx.Error(c,500,"enrollment_operation_failed","enrollment operation failed")}}
func(ctrl *EnrollmentController)List(c *gin.Context){v,e:=ctrl.service.List();if e!=nil{enrollmentError(c,e);return};c.JSON(200,v)}
func(ctrl *EnrollmentController)Get(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_enrollment_id","invalid enrollment id");return};v,e:=ctrl.service.Get(id);if e!=nil{enrollmentError(c,e);return};c.JSON(200,v)}
func(ctrl *EnrollmentController)Create(c *gin.Context){var r enrollmentRequest;if e:=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};v,e:=ctrl.service.Create(models.StudentEnrollment{StudentID:r.StudentID,AcademicSessionID:r.AcademicSessionID,ClassID:r.ClassID,SectionID:r.SectionID,Status:r.Status});if e!=nil{enrollmentError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"student_enrollment.create","student_enrollment",&v.ID,nil);c.JSON(http.StatusCreated,v)}
func(ctrl *EnrollmentController)Update(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_enrollment_id","invalid enrollment id");return};var r enrollmentRequest;if e=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};v,e:=ctrl.service.Get(id);if e!=nil{enrollmentError(c,e);return};v.StudentID,v.AcademicSessionID,v.ClassID,v.SectionID,v.Status=r.StudentID,r.AcademicSessionID,r.ClassID,r.SectionID,r.Status;if e=ctrl.service.Update(v);e!=nil{enrollmentError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"student_enrollment.update","student_enrollment",&v.ID,nil);c.JSON(200,v)}
func(ctrl *EnrollmentController)Delete(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_enrollment_id","invalid enrollment id");return};if e=ctrl.service.Delete(id);e!=nil{enrollmentError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"student_enrollment.delete","student_enrollment",&id,nil);c.JSON(200,gin.H{"message":"student enrollment deleted"})}
