package controller

import("errors";"net/http";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/audit";"github.com/onoja217/users-management-app/internal/httpx";"github.com/onoja217/users-management-app/internal/middleware";"github.com/onoja217/users-management-app/internal/service")
type GuardianController struct{service *service.GuardianService}
func NewGuardianController(s *service.GuardianService)*GuardianController{return &GuardianController{service:s}}
func guardianError(c *gin.Context,e error){switch{case errors.Is(e,service.ErrGuardianForbidden):httpx.Error(c,403,"guardian_forbidden","student is not linked to this guardian");case errors.Is(e,service.ErrGuardianInvalid):httpx.Error(c,400,"invalid_guardian_request","invalid guardian request");default:httpx.Error(c,500,"guardian_operation_failed","guardian operation failed")}}
func(ctrl *GuardianController)context(c *gin.Context)(uuid.UUID,uuid.UUID,bool){gid,e:=uuid.Parse(c.GetString("user_id"));if e!=nil{httpx.Error(c,401,"invalid_user","invalid authenticated user");return uuid.Nil,uuid.Nil,false};sid,ok:=middleware.SchoolIDFromContext(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return uuid.Nil,uuid.Nil,false};return gid,sid,true}
func(ctrl *GuardianController)Terms(c *gin.Context){gid,schoolID,ok:=ctrl.context(c);if !ok{return};sid,e:=uuid.Parse(c.Query("student_id"));if e!=nil||sid==uuid.Nil{httpx.Error(c,400,"invalid_student_id","student_id is required");return};sessionID,e:=uuid.Parse(c.Query("academic_session_id"));if e!=nil||sessionID==uuid.Nil{httpx.Error(c,400,"invalid_session_id","academic_session_id is required");return};v,e:=ctrl.service.Terms(schoolID,gid,sid,sessionID);if e!=nil{guardianError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *GuardianController)Children(c *gin.Context){gid,schoolID,ok:=ctrl.context(c);if !ok{return};v,e:=ctrl.service.Children(schoolID,gid);if e!=nil{guardianError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *GuardianController)withChild(c *gin.Context,fn func(uuid.UUID,uuid.UUID)(interface{},error)){gid,schoolID,ok:=ctrl.context(c);if !ok{return};sid,e:=uuid.Parse(c.Param("studentId"));if e!=nil{httpx.Error(c,400,"invalid_student_id","invalid student id");return};v,e:=fn(schoolID,sid);if e!=nil{guardianError(c,e);return};_ = gid;c.JSON(http.StatusOK,v)}
func(ctrl *GuardianController)Attendance(c *gin.Context){ctrl.withChild(c,func(schoolID,sid uuid.UUID)(interface{},error){gid,_:=uuid.Parse(c.GetString("user_id")); sessionID,e:=uuid.Parse(c.Query("academic_session_id"));if e!=nil||sessionID==uuid.Nil{return nil,service.ErrGuardianInvalid};termID,e:=uuid.Parse(c.Query("term_id"));if e!=nil||termID==uuid.Nil{return nil,service.ErrGuardianInvalid};return ctrl.service.Attendance(schoolID,gid,sid,sessionID,termID)})}
func(ctrl *GuardianController)Timetable(c *gin.Context){ctrl.withChild(c,func(schoolID,sid uuid.UUID)(interface{},error){gid,_:=uuid.Parse(c.GetString("user_id")); sessionID,e:=uuid.Parse(c.Query("academic_session_id"));if e!=nil||sessionID==uuid.Nil{return nil,service.ErrGuardianInvalid};termID,e:=uuid.Parse(c.Query("term_id"));if e!=nil||termID==uuid.Nil{return nil,service.ErrGuardianInvalid};return ctrl.service.Timetable(schoolID,gid,sid,sessionID,termID)})}
func(ctrl *GuardianController)Invoices(c *gin.Context){ctrl.withChild(c,func(schoolID,sid uuid.UUID)(interface{},error){gid,_:=uuid.Parse(c.GetString("user_id")); sessionID,e:=uuid.Parse(c.Query("academic_session_id"));if e!=nil||sessionID==uuid.Nil{return nil,service.ErrGuardianInvalid};termID,e:=uuid.Parse(c.Query("term_id"));if e!=nil||termID==uuid.Nil{return nil,service.ErrGuardianInvalid};return ctrl.service.Invoices(schoolID,gid,sid,sessionID,termID)})}
func(ctrl *GuardianController)Payments(c *gin.Context){ctrl.withChild(c,func(schoolID,sid uuid.UUID)(interface{},error){gid,_:=uuid.Parse(c.GetString("user_id")); sessionID,e:=uuid.Parse(c.Query("academic_session_id"));if e!=nil||sessionID==uuid.Nil{return nil,service.ErrGuardianInvalid};termID,e:=uuid.Parse(c.Query("term_id"));if e!=nil||termID==uuid.Nil{return nil,service.ErrGuardianInvalid};return ctrl.service.Payments(schoolID,gid,sid,sessionID,termID)})}
func(ctrl *GuardianController)ReportCard(c *gin.Context){gid,schoolID,ok:=ctrl.context(c);if !ok{return};sid,e:=uuid.Parse(c.Param("studentId"));if e!=nil{httpx.Error(c,400,"invalid_student_id","invalid student id");return};tid,e:=uuid.Parse(c.Param("termId"));if e!=nil{httpx.Error(c,400,"invalid_term_id","invalid term id");return};sessionID,e:=uuid.Parse(c.Query("academic_session_id"));if e!=nil||sessionID==uuid.Nil{httpx.Error(c,400,"invalid_session_id","academic_session_id is required");return};v,e:=ctrl.service.ReportCard(schoolID,gid,sid,sessionID,tid);if e!=nil{guardianError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *GuardianController)CreateLink(c *gin.Context){_,schoolID,ok:=ctrl.context(c);if !ok{return};var r struct{GuardianUserID uuid.UUID `json:"guardian_user_id" binding:"required"`;StudentID uuid.UUID `json:"student_id" binding:"required"`;Relationship string `json:"relationship" binding:"required,max=40"`;Primary bool `json:"primary"`};if e:=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};v,e:=ctrl.service.CreateLink(schoolID,r.GuardianUserID,r.StudentID,r.Relationship,r.Primary);if e!=nil{guardianError(c,e);return};actor,_,ok:=ctrl.context(c);if !ok{return};_=audit.Record(ctrl.service.DB(),c,&actor,"guardian.link.create","guardian_relationship",&v.ID,nil);c.JSON(http.StatusCreated,v)}
