package controller

import("errors";"net/http";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/audit";"github.com/onoja217/users-management-app/internal/httpx";"github.com/onoja217/users-management-app/internal/service")
type GuardianController struct{service *service.GuardianService}
func NewGuardianController(s *service.GuardianService)*GuardianController{return &GuardianController{service:s}}
func guardianError(c *gin.Context,e error){switch{case errors.Is(e,service.ErrGuardianForbidden):httpx.Error(c,403,"guardian_forbidden","student is not linked to this guardian");case errors.Is(e,service.ErrGuardianInvalid):httpx.Error(c,400,"invalid_guardian_request","invalid guardian request");default:httpx.Error(c,500,"guardian_operation_failed","guardian operation failed")}}
func(ctrl *GuardianController)user(c *gin.Context)(uuid.UUID,bool){id,e:=uuid.Parse(c.GetString("user_id"));if e!=nil{httpx.Error(c,401,"invalid_user","invalid authenticated user");return uuid.Nil,false};return id,true}
func(ctrl *GuardianController)Terms(c *gin.Context){gid,ok:=ctrl.user(c);if !ok{return};v,e:=ctrl.service.Terms(gid);if e!=nil{guardianError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *GuardianController)Children(c *gin.Context){gid,ok:=ctrl.user(c);if !ok{return};v,e:=ctrl.service.Children(gid);if e!=nil{guardianError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *GuardianController)withChild(c *gin.Context,fn func(uuid.UUID)(interface{},error)){if _,ok:=ctrl.user(c);!ok{return};sid,e:=uuid.Parse(c.Param("studentId"));if e!=nil{httpx.Error(c,400,"invalid_student_id","invalid student id");return};v,e:=fn(sid);if e!=nil{guardianError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *GuardianController)Attendance(c *gin.Context){ctrl.withChild(c,func(sid uuid.UUID)(interface{},error){gid,_:=uuid.Parse(c.GetString("user_id"));return ctrl.service.Attendance(gid,sid)})}
func(ctrl *GuardianController)Timetable(c *gin.Context){ctrl.withChild(c,func(sid uuid.UUID)(interface{},error){gid,_:=uuid.Parse(c.GetString("user_id"));return ctrl.service.Timetable(gid,sid)})}
func(ctrl *GuardianController)Invoices(c *gin.Context){ctrl.withChild(c,func(sid uuid.UUID)(interface{},error){gid,_:=uuid.Parse(c.GetString("user_id"));return ctrl.service.Invoices(gid,sid)})}
func(ctrl *GuardianController)Payments(c *gin.Context){ctrl.withChild(c,func(sid uuid.UUID)(interface{},error){gid,_:=uuid.Parse(c.GetString("user_id"));return ctrl.service.Payments(gid,sid)})}
func(ctrl *GuardianController)ReportCard(c *gin.Context){gid,ok:=ctrl.user(c);if !ok{return};sid,e:=uuid.Parse(c.Param("studentId"));if e!=nil{httpx.Error(c,400,"invalid_student_id","invalid student id");return};tid,e:=uuid.Parse(c.Param("termId"));if e!=nil{httpx.Error(c,400,"invalid_term_id","invalid term id");return};v,e:=ctrl.service.ReportCard(gid,sid,tid);if e!=nil{guardianError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *GuardianController)CreateLink(c *gin.Context){var r struct{GuardianUserID uuid.UUID `json:"guardian_user_id" binding:"required"`;StudentID uuid.UUID `json:"student_id" binding:"required"`;Relationship string `json:"relationship" binding:"required,max=40"`;Primary bool `json:"primary"`};if e:=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};v,e:=ctrl.service.CreateLink(r.GuardianUserID,r.StudentID,r.Relationship,r.Primary);if e!=nil{guardianError(c,e);return};actor,ok:=ctrl.user(c);if !ok{return};_=audit.Record(ctrl.service.DB(),c,&actor,"guardian.link.create","guardian_relationship",&v.ID,nil);c.JSON(http.StatusCreated,v)}
