package controller
import("errors";"net/http";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/audit";"github.com/onoja217/users-management-app/internal/httpx"
"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/service")
type NotificationController struct{service *service.NotificationService}
func NewNotificationController(s *service.NotificationService)*NotificationController{return &NotificationController{s}}
func(cn *NotificationController)uid(c *gin.Context)(uuid.UUID,bool){id,e:=uuid.Parse(c.GetString("user_id"));if e!=nil{httpx.Error(c,401,"invalid_user","invalid authenticated user");return uuid.Nil,false};return id,true}
func(cn *NotificationController)error(c *gin.Context,e error){if errors.Is(e,service.ErrNotificationInvalid){httpx.Error(c,400,"invalid_notification_request","invalid notification request")}else if errors.Is(e,service.ErrNotificationNotFound){httpx.Error(c,404,"notification_not_found","notification not found")}else{httpx.Error(c,500,"notification_operation_failed","notification operation failed")}}
func(cn *NotificationController)CreateAnnouncement(c *gin.Context){uid,ok:=cn.uid(c);if !ok{return};var r struct{Title,Body,Category,Audience string;ClassID *uuid.UUID `json:"class_id"`};if e:=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};a,e:=cn.service.CreateAnnouncement(models.Announcement{CreatedBy:uid,Title:r.Title,Body:r.Body,Category:r.Category,Audience:r.Audience,ClassID:r.ClassID});if e!=nil{cn.error(c,e);return};_=audit.Record(cn.service.DB(),c,&uid,"announcement.create","announcement",&a.ID,nil);c.JSON(http.StatusCreated,a)}
func(cn *NotificationController)Publish(c *gin.Context){uid,ok:=cn.uid(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_id","invalid announcement id");return};n,e:=cn.service.Publish(id);if e!=nil{cn.error(c,e);return};_=audit.Record(cn.service.DB(),c,&uid,"announcement.publish","announcement",&id,map[string]interface{}{"notifications":n});c.JSON(http.StatusOK,gin.H{"notifications":n})}
func(cn *NotificationController)Announcements(c *gin.Context){v,e:=cn.service.ListAnnouncements();if e!=nil{cn.error(c,e);return};c.JSON(http.StatusOK,v)}
func(cn *NotificationController)Mine(c *gin.Context){uid,ok:=cn.uid(c);if !ok{return};v,e:=cn.service.List(uid);if e!=nil{cn.error(c,e);return};c.JSON(http.StatusOK,v)}
func(cn *NotificationController)Read(c *gin.Context){uid,ok:=cn.uid(c);if !ok{return};id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_id","invalid notification id");return};if e=cn.service.MarkRead(uid,id);e!=nil{cn.error(c,e);return};c.Status(http.StatusNoContent)}
