package controller

import (
 "errors"
 "strings"
 "github.com/gin-gonic/gin"
 "github.com/google/uuid"
 "github.com/onoja217/users-management-app/internal/auth"
 "github.com/onoja217/users-management-app/internal/authz"
 "github.com/onoja217/users-management-app/internal/audit"
 "github.com/onoja217/users-management-app/internal/httpx"
 "github.com/onoja217/users-management-app/internal/models"
 "gorm.io/gorm"
)
type PlatformSchoolController struct{DB *gorm.DB}
func NewPlatformSchoolController(db *gorm.DB)*PlatformSchoolController{return &PlatformSchoolController{DB:db}}
type CreatePlatformSchoolRequest struct{Name string `json:"name" binding:"required,min=2,max=160"`;Code string `json:"code" binding:"required,min=2,max=50"`;AdminName string `json:"admin_name" binding:"required,min=2,max=100"`;AdminEmail string `json:"admin_email" binding:"required,email,max=255"`;AdminPassword string `json:"admin_password" binding:"required,min=8,max=128"`}
type UpdatePlatformSchoolRequest struct{Name *string `json:"name" binding:"omitempty,min=2,max=160"`;Code *string `json:"code" binding:"omitempty,min=2,max=50"`;Status *string `json:"status" binding:"omitempty,oneof=pending active suspended"`}
func(ctrl *PlatformSchoolController)List(c *gin.Context){var schools []models.School;if err:=ctrl.DB.Order("name ASC").Find(&schools).Error;err!=nil{httpx.Error(c,500,"schools_list_failed","failed to load schools");return};type item struct{models.School;UserCount int64 `json:"user_count"`};out:=make([]item,0,len(schools));for _,s:=range schools{var n int64;if err:=ctrl.DB.Model(&models.User{}).Where("school_id = ?",s.ID).Count(&n).Error;err!=nil{httpx.Error(c,500,"schools_list_failed","failed to count school users");return};out=append(out,item{School:s,UserCount:n})};c.JSON(200,gin.H{"schools":out})}
func(ctrl *PlatformSchoolController)Create(c *gin.Context){var req CreatePlatformSchoolRequest;if err:=c.ShouldBindJSON(&req);err!=nil{httpx.Validation(c,httpx.ValidationErrors(err));return};name,code,email:=strings.TrimSpace(req.Name),strings.ToUpper(strings.TrimSpace(req.Code)),strings.ToLower(strings.TrimSpace(req.AdminEmail));hash,err:=auth.HashPassword(req.AdminPassword);if err!=nil{httpx.Error(c,500,"password_hash_failed","failed to secure administrator password");return};school:=models.School{ID:uuid.New(),Name:name,Code:code,Status:models.SchoolStatusActive};admin:=models.User{ID:uuid.New(),Name:strings.TrimSpace(req.AdminName),Email:email,PasswordHash:hash,Role:authz.RoleSchoolAdmin,Active:true};err=ctrl.DB.Transaction(func(tx *gorm.DB)error{var existing models.School;if e:=tx.Where("lower(code) = ?",strings.ToLower(code)).First(&existing).Error;e==nil{return gorm.ErrDuplicatedKey}else if !errors.Is(e,gorm.ErrRecordNotFound){return e};var existingUser models.User;if e:=tx.Where("lower(email) = ?",email).First(&existingUser).Error;e==nil{return gorm.ErrDuplicatedKey}else if !errors.Is(e,gorm.ErrRecordNotFound){return e};if e:=tx.Create(&school).Error;e!=nil{return e};admin.SchoolID=&school.ID;return tx.Create(&admin).Error});if err!=nil{if errors.Is(err,gorm.ErrDuplicatedKey){httpx.Error(c,409,"school_or_email_exists","school code or administrator email already exists")}else{httpx.Error(c,500,"school_create_failed","failed to create school")};return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.DB,c,&actor,"school.provision","school",&school.ID,map[string]interface{}{"code":school.Code,"admin_user_id":admin.ID});c.JSON(201,gin.H{"school":school,"administrator":gin.H{"id":admin.ID,"name":admin.Name,"email":admin.Email,"role":admin.Role}})}
func(ctrl *PlatformSchoolController)Update(c *gin.Context){id,err:=uuid.Parse(c.Param("id"));if err!=nil{httpx.Error(c,400,"invalid_school_id","invalid school id");return};var req UpdatePlatformSchoolRequest;if err=c.ShouldBindJSON(&req);err!=nil{httpx.Validation(c,httpx.ValidationErrors(err));return};var school models.School;if err=ctrl.DB.First(&school,"id = ?",id).Error;err!=nil{httpx.Error(c,404,"school_not_found","school not found");return};updates:=map[string]interface{}{};if req.Name!=nil{v:=strings.TrimSpace(*req.Name);if v==""{httpx.Error(c,400,"invalid_school_name","school name is required");return};updates["name"]=v};if req.Code!=nil{v:=strings.ToUpper(strings.TrimSpace(*req.Code));if v==""{httpx.Error(c,400,"invalid_school_code","school code is required");return};updates["code"]=v};if req.Status!=nil{updates["status"]=strings.TrimSpace(*req.Status)};if len(updates)==0{c.JSON(200,school);return};if err=ctrl.DB.Model(&school).Updates(updates).Error;err!=nil{httpx.Error(c,409,"school_update_failed","unable to update school; code may already exist");return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.DB,c,&actor,"school.update","school",&school.ID,updates);if err=ctrl.DB.First(&school,"id = ?",id).Error;err!=nil{httpx.Error(c,500,"school_read_failed","failed to reload school");return};c.JSON(200,school)}
