package controller

import (
 "errors"
 "fmt"
 "net/http"
 "strings"
 "github.com/gin-gonic/gin"
 "github.com/google/uuid"
 "github.com/onoja217/users-management-app/internal/audit"
 "github.com/onoja217/users-management-app/internal/httpx"
 "github.com/onoja217/users-management-app/internal/middleware"
 "github.com/onoja217/users-management-app/internal/models"
 "github.com/onoja217/users-management-app/internal/service"
 "gorm.io/gorm"
)

type SchoolContentController struct{content *service.SchoolContentService;storage *service.SchoolMediaStorage;db *gorm.DB}
func NewSchoolContentController(content *service.SchoolContentService,storage *service.SchoolMediaStorage,db *gorm.DB)*SchoolContentController{return &SchoolContentController{content:content,storage:storage,db:db}}

type blogRequest struct{Title string `json:"title" binding:"required,min=2,max=240"`;Slug string `json:"slug" binding:"omitempty,max=240"`;Excerpt string `json:"excerpt" binding:"max=500"`;Content string `json:"content" binding:"required"`;FeaturedImageURL string `json:"featured_image_url" binding:"omitempty,max=1200"`;Status string `json:"status" binding:"omitempty,oneof=draft published archived"`;Featured bool `json:"featured"`}
type albumRequest struct{Title string `json:"title" binding:"required,min=2,max=180"`;Slug string `json:"slug" binding:"omitempty,max=200"`;Description string `json:"description" binding:"max=1000"`;CoverImageURL string `json:"cover_image_url" binding:"omitempty,max=1200"`;Status string `json:"status" binding:"omitempty,oneof=draft published archived"`;Featured bool `json:"featured"`}

func schoolID(c *gin.Context)(uuid.UUID,bool){id,ok:=middleware.SchoolIDFromContext(c);return id,ok}
func actorID(c *gin.Context)uuid.UUID{id,_:=uuid.Parse(c.GetString("user_id"));return id}
func contentError(c *gin.Context,err error){switch{case errors.Is(err,service.ErrContentNotFound):httpx.Error(c,404,"content_not_found","content not found");case errors.Is(err,service.ErrContentSlugExists):httpx.Error(c,409,"content_slug_exists","content slug already exists");case errors.Is(err,service.ErrContentInvalidStatus):httpx.Error(c,400,"content_invalid_status","invalid content status");default:httpx.Error(c,500,"content_operation_failed","content operation failed")}}

func(ctrl *SchoolContentController)ListBlogs(c *gin.Context){id,ok:=schoolID(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};v,e:=ctrl.content.ListBlogs(id);if e!=nil{contentError(c,e);return};c.JSON(200,gin.H{"posts":v})}
func(ctrl *SchoolContentController)CreateBlog(c *gin.Context){id,ok:=schoolID(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};var r blogRequest;if e:=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};p,e:=ctrl.content.CreateBlog(id,actorID(c),&models.BlogPost{Title:r.Title,Slug:r.Slug,Excerpt:r.Excerpt,Content:r.Content,FeaturedImageURL:r.FeaturedImageURL,Status:r.Status,Featured:r.Featured});if e!=nil{contentError(c,e);return};actor:=actorID(c);_=audit.Record(ctrl.db,c,&actor,"content.blog.create","blog_post",&p.ID,nil);c.JSON(201,p)}
func(ctrl *SchoolContentController)UpdateBlog(c *gin.Context){id,ok:=schoolID(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};pid,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_content_id","invalid content id");return};var r map[string]interface{};if e=c.ShouldBindJSON(&r);e!=nil{httpx.Error(c,400,"invalid_content","invalid content payload");return};p,e:=ctrl.content.UpdateBlog(id,pid,r);if e!=nil{contentError(c,e);return};c.JSON(200,p)}
func(ctrl *SchoolContentController)DeleteBlog(c *gin.Context){id,ok:=schoolID(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};pid,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_content_id","invalid content id");return};if e=ctrl.content.DeleteBlog(id,pid);e!=nil{contentError(c,e);return};c.JSON(200,gin.H{"deleted":true})}
func(ctrl *SchoolContentController)PublishBlog(c *gin.Context){id,ok:=schoolID(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};pid,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_content_id","invalid content id");return};p,e:=ctrl.content.UpdateBlog(id,pid,map[string]interface{}{"status":models.ContentPublished});if e!=nil{contentError(c,e);return};c.JSON(200,p)}

func(ctrl *SchoolContentController)ListAlbums(c *gin.Context){id,ok:=schoolID(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};v,e:=ctrl.content.ListAlbums(id);if e!=nil{contentError(c,e);return};c.JSON(200,gin.H{"albums":v})}
func(ctrl *SchoolContentController)CreateAlbum(c *gin.Context){id,ok:=schoolID(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};var r albumRequest;if e:=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};a,e:=ctrl.content.CreateAlbum(id,&models.GalleryAlbum{Title:r.Title,Slug:r.Slug,Description:r.Description,CoverImageURL:r.CoverImageURL,Status:r.Status,Featured:r.Featured});if e!=nil{contentError(c,e);return};c.JSON(201,a)}
func(ctrl *SchoolContentController)UpdateAlbum(c *gin.Context){id,ok:=schoolID(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};aid,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_content_id","invalid content id");return};var r map[string]interface{};if e=c.ShouldBindJSON(&r);e!=nil{httpx.Error(c,400,"invalid_content","invalid content payload");return};a,e:=ctrl.content.UpdateAlbum(id,aid,r);if e!=nil{contentError(c,e);return};c.JSON(200,a)}
func(ctrl *SchoolContentController)DeleteAlbum(c *gin.Context){id,ok:=schoolID(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};aid,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_content_id","invalid content id");return};if e=ctrl.content.DeleteAlbum(id,aid);e!=nil{contentError(c,e);return};c.JSON(200,gin.H{"deleted":true})}
func(ctrl *SchoolContentController)UploadImage(c *gin.Context){id,ok:=schoolID(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};if ctrl.storage==nil{httpx.Error(c,503,"media_storage_unavailable","media storage is not configured");return};aid,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_album_id","invalid album id");return};f,h,e:=c.Request.FormFile("image");if e!=nil{httpx.Error(c,400,"image_required","image file is required");return};defer f.Close();ct:=h.Header.Get("Content-Type");if ct==""{ct="application/octet-stream"};url,e:=ctrl.storage.Upload(id,"gallery/"+aid.String(),h.Filename,ct,f,h.Size);if e!=nil{httpx.Error(c,400,"image_upload_failed",fmt.Sprintf("%v",e));return};img,e:=ctrl.content.AddImage(id,actorID(c),aid,&models.GalleryImage{ImageURL:url,Caption:c.PostForm("caption"),AltText:c.PostForm("alt_text")});if e!=nil{contentError(c,e);return};c.JSON(201,img)}
func(ctrl *SchoolContentController)DeleteImage(c *gin.Context){id,ok:=schoolID(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return};iid,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_image_id","invalid image id");return};if e=ctrl.content.DeleteImage(id,iid);e!=nil{contentError(c,e);return};c.JSON(200,gin.H{"deleted":true})}

func(ctrl *SchoolContentController)PublicSchool(c *gin.Context){slug:=strings.TrimSpace(c.Param("slug"));var school models.School;if e:=ctrl.db.Where("lower(slug)=lower(?)",slug).First(&school).Error;e!=nil{httpx.Error(c,404,"school_not_found","school not found");return};if school.Status!=models.SchoolStatusActive{httpx.Error(c,410,"school_inactive","school account is currently inactive");return};blogs,albums,e:=ctrl.content.PublicHome(school.ID);if e!=nil{httpx.Error(c,500,"public_content_failed","failed to load school content");return};c.JSON(200,gin.H{"school":school,"featured_blog":blogs,"featured_gallery":albums})}
func(ctrl *SchoolContentController)PublicBlogs(c *gin.Context){slug:=strings.TrimSpace(c.Param("slug"));var school models.School;if e:=ctrl.db.Where("lower(slug)=lower(?)",slug).First(&school).Error;e!=nil{httpx.Error(c,404,"school_not_found","school not found");return};if school.Status!=models.SchoolStatusActive{httpx.Error(c,410,"school_inactive","school account is currently inactive");return};v,e:=ctrl.content.PublicBlogs(school.ID);if e!=nil{contentError(c,e);return};c.JSON(200,gin.H{"school":gin.H{"id":school.ID,"name":school.Name,"slug":school.Slug,"logo_url":school.LogoURL},"posts":v})}
func(ctrl *SchoolContentController)PublicBlog(c *gin.Context){slug:=strings.TrimSpace(c.Param("slug"));var school models.School;if e:=ctrl.db.Where("lower(slug)=lower(?)",slug).First(&school).Error;e!=nil{httpx.Error(c,404,"school_not_found","school not found");return};p,e:=ctrl.content.PublicBlog(school.ID,c.Param("post"));if e!=nil{contentError(c,e);return};c.JSON(200,p)}
func(ctrl *SchoolContentController)PublicAlbums(c *gin.Context){slug:=strings.TrimSpace(c.Param("slug"));var school models.School;if e:=ctrl.db.Where("lower(slug)=lower(?)",slug).First(&school).Error;e!=nil{httpx.Error(c,404,"school_not_found","school not found");return};a,e:=ctrl.content.PublicAlbums(school.ID);if e!=nil{contentError(c,e);return};c.JSON(200,gin.H{"albums":a})}
func(ctrl *SchoolContentController)PublicAlbum(c *gin.Context){slug:=strings.TrimSpace(c.Param("slug"));var school models.School;if e:=ctrl.db.Where("lower(slug)=lower(?)",slug).First(&school).Error;e!=nil{httpx.Error(c,404,"school_not_found","school not found");return};a,imgs,e:=ctrl.content.PublicAlbum(school.ID,c.Param("album"));if e!=nil{contentError(c,e);return};c.JSON(200,gin.H{"album":a,"images":imgs})}
