package controller
import("errors";"net/http";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/httpx";"github.com/onoja217/users-management-app/internal/middleware";"github.com/onoja217/users-management-app/internal/service")
type StudentPortalController struct{service *service.StudentPortalService}
func NewStudentPortalController(s *service.StudentPortalService)*StudentPortalController{return &StudentPortalController{s}}
func studentPortalError(c *gin.Context,e error){switch{case errors.Is(e,service.ErrStudentPortalForbidden):httpx.Error(c,403,"student_portal_forbidden","student portal access is restricted to the authenticated student");case errors.Is(e,service.ErrStudentPortalNotFound):httpx.Error(c,404,"student_portal_not_found","student portal record not found");default:httpx.Error(c,500,"student_portal_operation_failed","student portal operation failed")}}
func(ctrl *StudentPortalController)context(c *gin.Context)(uuid.UUID,uuid.UUID,bool){uid,e:=uuid.Parse(c.GetString("user_id"));if e!=nil{httpx.Error(c,401,"invalid_user","invalid authenticated user");return uuid.Nil,uuid.Nil,false};sid,ok:=middleware.SchoolIDFromContext(c);if !ok{httpx.Error(c,403,"school_context_required","school context required");return uuid.Nil,uuid.Nil,false};return uid,sid,true}
func(ctrl *StudentPortalController)Profile(c *gin.Context){uid,sid,ok:=ctrl.context(c);if !ok{return};v,e:=ctrl.service.Profile(sid,uid);if e!=nil{studentPortalError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *StudentPortalController)Enrollment(c *gin.Context){uid,sid,ok:=ctrl.context(c);if !ok{return};v,e:=ctrl.service.Enrollment(sid,uid);if e!=nil{studentPortalError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *StudentPortalController)Terms(c *gin.Context){uid,sid,ok:=ctrl.context(c);if !ok{return};v,e:=ctrl.service.Terms(sid,uid);if e!=nil{studentPortalError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *StudentPortalController)Attendance(c *gin.Context){uid,sid,ok:=ctrl.context(c);if !ok{return};v,e:=ctrl.service.Attendance(sid,uid);if e!=nil{studentPortalError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *StudentPortalController)Timetable(c *gin.Context){uid,sid,ok:=ctrl.context(c);if !ok{return};v,e:=ctrl.service.Timetable(sid,uid);if e!=nil{studentPortalError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *StudentPortalController)ReportCard(c *gin.Context){uid,sid,ok:=ctrl.context(c);if !ok{return};tid,e:=uuid.Parse(c.Param("termId"));if e!=nil{httpx.Error(c,400,"invalid_term_id","invalid term id");return};v,e:=ctrl.service.ReportCard(sid,uid,tid);if e!=nil{studentPortalError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *StudentPortalController)Invoices(c *gin.Context){uid,sid,ok:=ctrl.context(c);if !ok{return};v,e:=ctrl.service.Invoices(sid,uid);if e!=nil{studentPortalError(c,e);return};c.JSON(http.StatusOK,v)}
func(ctrl *StudentPortalController)Payments(c *gin.Context){uid,sid,ok:=ctrl.context(c);if !ok{return};v,e:=ctrl.service.Payments(sid,uid);if e!=nil{studentPortalError(c,e);return};c.JSON(http.StatusOK,v)}
