package controller

import ("errors";"net/http";"github.com/gin-gonic/gin";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/audit";"github.com/onoja217/users-management-app/internal/httpx";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/service")
type TimetableController struct{service *service.TimetableService}
func NewTimetableController(s *service.TimetableService)*TimetableController{return &TimetableController{service:s}}
func timetableError(c *gin.Context,e error){switch{case errors.Is(e,service.ErrTimetableNotFound):httpx.Error(c,404,"timetable_not_found","timetable entry not found");case errors.Is(e,service.ErrTimetableConflict):httpx.Error(c,409,"timetable_conflict","teacher or class/section timetable conflict");case errors.Is(e,service.ErrTimetableInvalid):httpx.Error(c,400,"invalid_timetable","invalid timetable entry");default:httpx.Error(c,500,"timetable_operation_failed","timetable operation failed")}}
type timetableRequest struct{AcademicSessionID uuid.UUID `json:"academic_session_id" binding:"required"`;TermID uuid.UUID `json:"term_id" binding:"required"`;TeacherAssignmentID uuid.UUID `json:"teacher_assignment_id" binding:"required"`;ClassID uuid.UUID `json:"class_id" binding:"required"`;SectionID *uuid.UUID `json:"section_id"`;DayOfWeek int `json:"day_of_week" binding:"required"`;StartTime string `json:"start_time" binding:"required"`;EndTime string `json:"end_time" binding:"required"`;Room string `json:"room"`;Active *bool `json:"active"`}
func(ctrl *TimetableController)save(c *gin.Context,update bool){var r timetableRequest;if e:=c.ShouldBindJSON(&r);e!=nil{httpx.Validation(c,httpx.ValidationErrors(e));return};v:=ctrl.service.Normalize(models.TimetableEntry{AcademicSessionID:r.AcademicSessionID,TermID:r.TermID,TeacherAssignmentID:r.TeacherAssignmentID,ClassID:r.ClassID,SectionID:r.SectionID,DayOfWeek:r.DayOfWeek,StartTime:r.StartTime,EndTime:r.EndTime,Room:r.Room,Active:true});if r.Active!=nil{v.Active=*r.Active};if update{id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_timetable_id","invalid timetable id");return};v.ID=id;if e=ctrl.service.Update(v);e!=nil{timetableError(c,e);return}}else{var e error;v,e=ctrl.service.Create(v);if e!=nil{timetableError(c,e);return}};actor,_:=uuid.Parse(c.GetString("user_id"));action:="timetable.create";if update{action="timetable.update"};_=audit.Record(ctrl.service.DB(),c,&actor,action,"timetable",&v.ID,nil);if update{c.JSON(200,v)}else{c.JSON(http.StatusCreated,v)}}
func(ctrl *TimetableController)List(c *gin.Context){v,e:=ctrl.service.List();if e!=nil{timetableError(c,e);return};c.JSON(200,v)}
func(ctrl *TimetableController)Get(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_timetable_id","invalid timetable id");return};v,e:=ctrl.service.Get(id);if e!=nil{timetableError(c,e);return};c.JSON(200,v)}
func(ctrl *TimetableController)Create(c *gin.Context){ctrl.save(c,false)}
func(ctrl *TimetableController)Update(c *gin.Context){ctrl.save(c,true)}
func(ctrl *TimetableController)Delete(c *gin.Context){id,e:=uuid.Parse(c.Param("id"));if e!=nil{httpx.Error(c,400,"invalid_timetable_id","invalid timetable id");return};if e=ctrl.service.Delete(id);e!=nil{timetableError(c,e);return};actor,_:=uuid.Parse(c.GetString("user_id"));_=audit.Record(ctrl.service.DB(),c,&actor,"timetable.delete","timetable",&id,nil);c.JSON(200,gin.H{"message":"timetable entry deleted"})}

func(ctrl *TimetableController)TeacherView(c *gin.Context){id,e:=uuid.Parse(c.GetString("user_id"));if e!=nil{httpx.Error(c,401,"invalid_user","invalid authenticated user");return};v,e:=ctrl.service.ListForTeacher(id);if e!=nil{timetableError(c,e);return};c.JSON(200,v)}
func(ctrl *TimetableController)StudentView(c *gin.Context){id,e:=uuid.Parse(c.GetString("user_id"));if e!=nil{httpx.Error(c,401,"invalid_user","invalid authenticated user");return};v,e:=ctrl.service.ListForStudent(id);if e!=nil{timetableError(c,e);return};c.JSON(200,v)}
