"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type User={id:string;name:string;email:string;role:string;active:boolean};
const roles=["super_admin","school_admin","teacher","student","parent","accountant","staff"];
async function api(path:string, options:RequestInit={}){const token=localStorage.getItem("access_token");const r=await fetch("/backend"+path,{...options,headers:{...options.headers,Authorization:"Bearer "+token,"Content-Type":"application/json"}});const text=await r.text();let d:any={};try{d=text?JSON.parse(text):{}}catch{d={error:text}}if(r.status===401)throw Error("Session expired");if(!r.ok)throw Error(d?.error?.message||d?.error||"Request failed");return d}
export default function UsersPage(){const[items,setItems]=useState<User[]>([]),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState("");
async function load(){try{const d=await api("/admin/users");setItems(Array.isArray(d)?d:d?.users||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load users")}}
useEffect(()=>{load()},[]);
async function action(id:string,action:string,body?:any){setBusy(id+action);setError("");try{await api("/admin/users/"+id+"/"+action,{method:action==="role"?"PUT":action==="delete"?"DELETE":"POST",body:body?JSON.stringify(body):undefined});await load()}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy("")}}
const filtered=items.filter(u=>(u.name+" "+u.email+" "+u.role).toLowerCase().includes(query.toLowerCase()));
return <div className="content standalone"><header className="topbar"><div><Link className="back" href="/dashboard">← Dashboard</Link><p className="eyebrow">ACCESS MANAGEMENT</p><h1>Users & Roles</h1><p className="muted">Manage accounts, activation status and school roles.</p></div></header>{error&&<div className="error banner">{error}</div>}<div className="panel"><div className="toolbar"><input placeholder="Search users..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}</small></td><td><select value={u.role} disabled={busy===u.id+"role"} onChange={e=>action(u.id,"role",{role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></td><td><span className={"pill "+(u.active?"active":"inactive")}>{u.active?"active":"inactive"}</span></td><td><div className="actions">{u.active?<button className="ghost" disabled={!!busy} onClick={()=>action(u.id,"deactivate")}>Deactivate</button>:<button disabled={!!busy} onClick={()=>action(u.id,"activate")}>Activate</button>}<button className="danger" disabled={!!busy} onClick={()=>{if(confirm("Delete this user?"))action(u.id,"delete")}}>Delete</button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No users found.</div>}</div></div></div>}
