"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";

type AnyRecord=Record<string,any>;
async function api(path:string,options:RequestInit={}){const token=localStorage.getItem("access_token");const r=await fetch("/backend"+path,{...options,headers:{...options.headers,Authorization:"Bearer "+token,"Content-Type":"application/json"}});const text=await r.text();let d:any={};try{d=text?JSON.parse(text):{}}catch{d={error:text}}if(r.status===401)throw Error("Session expired");if(!r.ok)throw Error(d?.error?.message||d?.error||"Request failed");return d}
const list=(d:any,key:string)=>Array.isArray(d)?d:d?.[key]||d?.data||[];
export default function Operations(){
 const[me,setMe]=useState<AnyRecord|null>(null),[tab,setTab]=useState("overview"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const[sessions,setSessions]=useState<AnyRecord[]>([]),[classes,setClasses]=useState<AnyRecord[]>([]),[subjects,setSubjects]=useState<AnyRecord[]>([]),[notifications,setNotifications]=useState<AnyRecord[]>([]);
 const[sessionName,setSessionName]=useState(""),[sessionStatus,setSessionStatus]=useState("active");
 const[className,setClassName]=useState(""),[classLevel,setClassLevel]=useState("1");
 const[subjectName,setSubjectName]=useState(""),[subjectCode,setSubjectCode]=useState("");
 const[announcement,setAnnouncement]=useState({title:"",body:"",category:"general",audience:"all",class_id:""});
 const[readBusy,setReadBusy]=useState("");
 const role=me?.role||"";
 const canManage=["super_admin","school_admin"].includes(role);
 const canTeach=["teacher","super_admin","school_admin"].includes(role);
 async function load(){try{setError("");const [m,s,c,sub,n]=await Promise.all([api("/me"),api("/admin/academic-sessions"),api("/admin/classes"),api("/admin/subjects"),api("/notifications")]);setMe(m);setSessions(list(s,"sessions"));setClasses(list(c,"classes"));setSubjects(list(sub,"subjects"));setNotifications(list(n,"notifications"))}catch(e){setError(e instanceof Error?e.message:"Unable to load operations")}}
 useEffect(()=>{load()},[]);
 async function create(path:string,body:any){setBusy(true);setError("");try{await api(path,{method:"POST",body:JSON.stringify(body)});await load()}catch(e){setError(e instanceof Error?e.message:"Operation failed")}finally{setBusy(false)}}
 async function publish(){if(!announcement.title||!announcement.body){setError("Announcement title and message are required.");return}setBusy(true);try{const a=await api("/admin/announcements",{method:"POST",body:JSON.stringify(announcement)});const id=a?.id||a?.announcement?.id;if(!id)throw Error("Announcement was created but no id was returned");await api("/admin/announcements/"+id+"/publish",{method:"POST"});setAnnouncement({title:"",body:"",category:"general",audience:"all",class_id:""});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to publish announcement")}finally{setBusy(false)}}
 async function markRead(id:string){setReadBusy(id);try{await api("/notifications/"+id+"/read",{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to mark notification read")}finally{setReadBusy("")}}
 const tabs=useMemo(()=>{const base=[["overview","Overview"],["setup","School setup"],["academic","Academic workflows"],["finance","Fees & payments"],["communication","Communication"]];return canTeach?base:base.filter(x=>x[0]!=="academic")},[canTeach]);
 return <div className="content standalone"><header className="topbar"><div><Link className="back" href="/dashboard">← Dashboard</Link><p className="eyebrow">SCHOOL OPERATIONS</p><h1>Operations workspace</h1><p className="muted">Role-aware workflows for administration, teaching, finance and communication.</p></div><div className="status"><span/> {role||"Loading role"}</div></header>
 {error&&<div className="error banner">{error}</div>}
 <div className="toolbar operations-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?"":"ghost light"} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==="overview"&&<><section className="stats"><Stat label="Academic sessions" value={sessions.length}/><Stat label="Classes" value={classes.length}/><Stat label="Subjects" value={subjects.length}/><Stat label="Unread notices" value={notifications.filter(n=>!n.read).length}/></section><section className="grid-2"><Panel title="Workflow map" text="Use the same workspace to move from school setup to daily operations."><div className="module-grid">{["Sessions & terms","Classes & sections","Teacher attendance","Assessments & results","Fees & invoices","Timetable","Parent portal","Notifications"].map(x=><div className="module" key={x}><div className="module-icon">✓</div><div><strong>{x}</strong><p>Connected to the live backend workflow.</p></div></div>)}</div></Panel><Panel title="Role access" text="Navigation is filtered by the signed-in role."><div className="role-list"><div><span>Administrator</span><strong>{canManage?"Manage":"Read"}</strong></div><div><span>Teacher</span><strong>{canTeach?"Teaching workflows":"Restricted"}</strong></div><div><span>Parent</span><strong>{role==="parent"?"Child portal":"Restricted"}</strong></div><div><span>Finance</span><strong>{["accountant","school_admin","super_admin"].includes(role)?"Available":"Restricted"}</strong></div></div></Panel></section></>}
 {tab==="setup"&&<Setup sessions={sessions} classes={classes} subjects={subjects} canManage={canManage} busy={busy} sessionName={sessionName} setSessionName={setSessionName} sessionStatus={sessionStatus} setSessionStatus={setSessionStatus} className={className} setClassName={setClassName} classLevel={classLevel} setClassLevel={setClassLevel} subjectName={subjectName} setSubjectName={setSubjectName} subjectCode={subjectCode} setSubjectCode={setSubjectCode} create={create}/>}
 {tab==="academic"&&<Academic canTeach={canTeach} sessions={sessions} classes={classes} busy={busy} create={create}/>}
 {tab==="finance"&&<Finance canManage={canManage} busy={busy}/>}
 {tab==="communication"&&<Communication announcement={announcement} setAnnouncement={setAnnouncement} publish={publish} busy={busy} notifications={notifications} markRead={markRead} readBusy={readBusy}/>}
 </div>
}
function Stat({label,value}:{label:string;value:number}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>Live records</small></div>}
function Panel(p:{title:string;text:string;children:React.ReactNode}){return <section className="panel"><div className="panel-head"><div><h2>{p.title}</h2><p>{p.text}</p></div></div>{p.children}</section>}
function Setup(p:any){return <><Panel title="Academic sessions" text="Create the school year/session that terms, enrollment and results depend on."><div className="form-grid"><label>Name<input value={p.sessionName} onChange={(e:any)=>p.setSessionName(e.target.value)} placeholder="2026/2027"/></label><label>Status<select value={p.sessionStatus} onChange={(e:any)=>p.setSessionStatus(e.target.value)}><option value="active">Active</option><option value="planned">Planned</option><option value="closed">Closed</option></select></label><div className="form-action"><button disabled={!p.canManage||p.busy} onClick={()=>p.create("/admin/academic-sessions",{name:p.sessionName,status:p.sessionStatus})}>Create session</button></div></div><Table rows={p.sessions} cols={["name","status"]}/></Panel><Panel title="Classes" text="Create classes before adding sections and teacher assignments."><div className="form-grid"><label>Name<input value={p.className} onChange={(e:any)=>p.setClassName(e.target.value)} placeholder="JSS 1"/></label><label>Level<input type="number" value={p.classLevel} onChange={(e:any)=>p.setClassLevel(e.target.value)} min="1"/></label><div className="form-action"><button disabled={!p.canManage||p.busy} onClick={()=>p.create("/admin/classes",{name:p.className,level:Number(p.classLevel)})}>Create class</button></div></div><Table rows={p.classes} cols={["name","level"]}/></Panel><Panel title="Subjects" text="Create the subjects used by teacher assignments and assessments."><div className="form-grid"><label>Name<input value={p.subjectName} onChange={(e:any)=>p.setSubjectName(e.target.value)} placeholder="Mathematics"/></label><label>Code<input value={p.subjectCode} onChange={(e:any)=>p.setSubjectCode(e.target.value)} placeholder="MTH"/></label><div className="form-action"><button disabled={!p.canManage||p.busy} onClick={()=>p.create("/admin/subjects",{name:p.subjectName,code:p.subjectCode})}>Create subject</button></div></div><Table rows={p.subjects} cols={["name","code"]}/></Panel></>}
function Academic({canTeach,sessions,classes,busy,create}:any){return <Panel title="Teaching workflows" text="The backend workflows are ready; use these entry points for daily teacher operations."><div className="module-grid"><Link className="module" href="/dashboard/attendance"><div className="module-icon">A</div><div><strong>Attendance</strong><p>Record present, absent, late or excused students.</p></div></Link><Link className="module" href="/dashboard/assessments"><div className="module-icon">S</div><div><strong>Assessments</strong><p>Create assessments and capture scores.</p></div></Link><Link className="module" href="/dashboard/results"><div className="module-icon">R</div><div><strong>Results</strong><p>Review results and report cards.</p></div></Link><Link className="module" href="/dashboard/timetable"><div className="module-icon">T</div><div><strong>Timetable</strong><p>View conflict-aware schedules.</p></div></Link></div><div className="empty">{canTeach?"Teacher/admin access is enabled for the academic workflow pages.":"Academic workflow access is restricted."}</div></Panel>}
function Finance({canManage,busy,}:any){return <Panel title="Finance workflows" text="Fees, invoices and payments are available from the finance workspace."><div className="module-grid"><Link className="module" href="/dashboard/finance"><div className="module-icon">F</div><div><strong>Fees & invoices</strong><p>Create fee items, invoices and record payments.</p></div></Link><Link className="module" href="/dashboard/finance"><div className="module-icon">₦</div><div><strong>Payment history</strong><p>Review balances and receipt-ready payment records.</p></div></Link></div><div className="empty">{canManage?"Finance administration is available for this role.":"Read-only or restricted finance access applies."}</div></Panel>}
function Communication(p:any){return <><Panel title="Publish announcement" text="Target the whole school, all parents, or a specific class."><div className="form-grid"><label>Title<input value={p.announcement.title} onChange={(e:any)=>p.setAnnouncement({...p.announcement,title:e.target.value})}/></label><label>Category<select value={p.announcement.category} onChange={(e:any)=>p.setAnnouncement({...p.announcement,category:e.target.value})}><option>general</option><option>attendance</option><option>fees</option><option>results</option><option>academic</option></select></label><label>Audience<select value={p.announcement.audience} onChange={(e:any)=>p.setAnnouncement({...p.announcement,audience:e.target.value})}><option value="all">Whole school</option><option value="parents">Parents</option><option value="class">Class</option></select></label><label>Class ID<input value={p.announcement.class_id} onChange={(e:any)=>p.setAnnouncement({...p.announcement,class_id:e.target.value})} placeholder="Required for class target"/></label><label style={{gridColumn:"1/-1"}}>Message<textarea value={p.announcement.body} onChange={(e:any)=>p.setAnnouncement({...p.announcement,body:e.target.value})} rows={5}/></label><div className="form-action"><button disabled={p.busy} onClick={p.publish}>{p.busy?"Publishing...":"Publish announcement"}</button></div></div></Panel><Panel title="Notification center" text="Unread state is stored per user."><div className="table-wrap"><table><thead><tr><th>Notification</th><th>Category</th><th>Status</th><th/></tr></thead><tbody>{p.notifications.map((n:any)=><tr key={n.id}><td><strong>{n.title}</strong><small>{n.body}</small></td><td>{n.category}</td><td><span className={"pill "+(n.read?"active":"")}>{n.read?"read":"unread"}</span></td><td>{!n.read&&<button disabled={p.readBusy===n.id} onClick={()=>p.markRead(n.id)}>{p.readBusy===n.id?"Saving...":"Mark read"}</button>}</td></tr>)}</tbody></table>{!p.notifications.length&&<div className="empty">No notifications yet.</div>}</div></Panel></>}
function Table({rows,cols}:{rows:any[];cols:string[]}){return <div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id||JSON.stringify(r)}>{cols.map(c=><td key={c}>{String(r[c]??"—")}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty">No records yet.</div>}</div>}
