-- Production schema for the Go/Gin school management API.
-- Supabase is the PostgreSQL production database; the API connects with
-- DATABASE_URL using the PostgreSQL driver. RLS is enabled on every table
-- and client roles are explicitly denied because application authorization
-- is enforced by the Go API.

create extension if not exists pgcrypto;

create table if not exists public.migrations(version bigint primary key,name text not null unique);
create table if not exists public.users(id uuid primary key,name text,email text unique,password_hash text,role text not null default 'student',active boolean not null default true);
create table if not exists public.refresh_tokens(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,token text unique,expires_at timestamptz not null,revoked boolean not null default false,created_at timestamptz default now());
create table if not exists public.sessions(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,refresh_token text unique,expires_at timestamptz not null,revoked boolean not null default false,user_agent text,ip text,created_at timestamptz default now());
create table if not exists public.password_reset_tokens(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,token text unique,expires_at timestamptz not null,used boolean default false,created_at timestamptz default now());
create table if not exists public.role_change_audits(id uuid primary key,actor_id uuid not null references public.users(id) on delete restrict,target_id uuid not null references public.users(id) on delete restrict,from_role text not null,to_role text not null,ip text,created_at timestamptz default now());
create table if not exists public.audit_logs(id uuid primary key,actor_id uuid references public.users(id) on delete set null,action text not null,resource text not null,resource_id uuid,ip text,metadata text,created_at timestamptz default now());
create table if not exists public.students(id uuid primary key,user_id uuid not null unique references public.users(id) on delete restrict,admission_number text not null unique,date_of_birth timestamptz,gender text,guardian_name text,guardian_phone text,guardian_email text,enrollment_status text not null default 'active',created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.academic_sessions(id uuid primary key,name text not null unique,start_date timestamptz not null,end_date timestamptz not null,status text not null default 'planned',created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.terms(id uuid primary key,academic_session_id uuid not null references public.academic_sessions(id) on delete cascade,name text not null,start_date timestamptz not null,end_date timestamptz not null,status text not null default 'planned',created_at timestamptz default now(),updated_at timestamptz default now(),unique(academic_session_id,name));
create table if not exists public.school_classes(id uuid primary key,name text not null unique,level bigint not null,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.sections(id uuid primary key,class_id uuid not null references public.school_classes(id) on delete cascade,name text not null,created_at timestamptz default now(),updated_at timestamptz default now(),unique(class_id,name));
create table if not exists public.student_enrollments(id uuid primary key,student_id uuid not null references public.students(id) on delete restrict,academic_session_id uuid not null references public.academic_sessions(id) on delete restrict,class_id uuid not null references public.school_classes(id) on delete restrict,section_id uuid not null references public.sections(id) on delete restrict,status text not null default 'active',enrolled_at timestamptz not null,created_at timestamptz default now(),updated_at timestamptz default now(),unique(student_id,academic_session_id));
create table if not exists public.subjects(id uuid primary key,code text not null unique,name text not null unique,description text,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.teacher_assignments(id uuid primary key,teacher_id uuid not null references public.users(id) on delete restrict,subject_id uuid not null references public.subjects(id) on delete restrict,academic_session_id uuid not null references public.academic_sessions(id) on delete restrict,term_id uuid not null references public.terms(id) on delete restrict,class_id uuid not null references public.school_classes(id) on delete restrict,section_id uuid references public.sections(id) on delete set null,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.attendance_records(id uuid primary key,enrollment_id uuid not null references public.student_enrollments(id) on delete restrict,term_id uuid not null references public.terms(id) on delete restrict,date date not null,status text not null,note text,created_at timestamptz default now(),updated_at timestamptz default now(),unique(enrollment_id,term_id,date));
create table if not exists public.assessments(id uuid primary key,teacher_assignment_id uuid not null references public.teacher_assignments(id) on delete restrict,title text not null,type text not null,max_score double precision not null,weight double precision not null,date date not null,created_at timestamptz default now(),updated_at timestamptz default now(),unique(teacher_assignment_id,title));
create table if not exists public.assessment_results(id uuid primary key,assessment_id uuid not null references public.assessments(id) on delete restrict,student_enrollment_id uuid not null references public.student_enrollments(id) on delete restrict,score double precision not null,created_at timestamptz default now(),updated_at timestamptz default now(),unique(assessment_id,student_enrollment_id));
create table if not exists public.fee_items(id uuid primary key,term_id uuid not null references public.terms(id) on delete restrict,name text not null,description text,amount double precision not null,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now(),unique(term_id,name));
create table if not exists public.invoices(id uuid primary key,invoice_number text not null unique,student_enrollment_id uuid not null references public.student_enrollments(id) on delete restrict,term_id uuid not null references public.terms(id) on delete restrict,due_date timestamptz not null,total_amount double precision not null,paid_amount double precision not null default 0,balance double precision not null default 0,status text not null default 'issued',created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.invoice_lines(id uuid primary key,invoice_id uuid not null references public.invoices(id) on delete cascade,fee_item_id uuid references public.fee_items(id) on delete restrict,description text not null,quantity double precision not null,unit_amount double precision not null,amount double precision not null);
create table if not exists public.payments(id uuid primary key,invoice_id uuid not null references public.invoices(id) on delete restrict,amount double precision not null,provider text not null,reference text not null unique,receipt_number text not null unique,status text not null default 'pending',paid_at timestamptz,metadata text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.timetable_entries(id uuid primary key,academic_session_id uuid not null references public.academic_sessions(id) on delete restrict,term_id uuid not null references public.terms(id) on delete restrict,teacher_assignment_id uuid not null references public.teacher_assignments(id) on delete restrict,class_id uuid not null references public.school_classes(id) on delete restrict,section_id uuid references public.sections(id) on delete set null,day_of_week bigint not null,start_time text not null,end_time text not null,room text,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.guardian_relationships(id uuid primary key,guardian_user_id uuid not null references public.users(id) on delete restrict,student_id uuid not null references public.students(id) on delete restrict,relationship text not null,"primary" boolean default false,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now(),unique(guardian_user_id,student_id));
create table if not exists public.announcements(id uuid primary key,created_by uuid not null references public.users(id) on delete restrict,title text not null,body text not null,category text not null,audience text not null,class_id uuid references public.school_classes(id) on delete set null,published boolean default false,published_at timestamptz,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.notifications(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,announcement_id uuid references public.announcements(id) on delete cascade,title text not null,body text not null,category text not null,read boolean default false,delivery_status text not null default 'pending',retry_count bigint default 0,last_error text,created_at timestamptz default now(),updated_at timestamptz default now(),unique(user_id,announcement_id));

alter table public.migrations enable row level security; alter table public.users enable row level security; alter table public.refresh_tokens enable row level security; alter table public.sessions enable row level security; alter table public.password_reset_tokens enable row level security; alter table public.role_change_audits enable row level security; alter table public.audit_logs enable row level security; alter table public.students enable row level security; alter table public.academic_sessions enable row level security; alter table public.terms enable row level security; alter table public.school_classes enable row level security; alter table public.sections enable row level security; alter table public.student_enrollments enable row level security; alter table public.subjects enable row level security; alter table public.teacher_assignments enable row level security; alter table public.attendance_records enable row level security; alter table public.assessments enable row level security; alter table public.assessment_results enable row level security; alter table public.fee_items enable row level security; alter table public.invoices enable row level security; alter table public.invoice_lines enable row level security; alter table public.payments enable row level security; alter table public.timetable_entries enable row level security; alter table public.guardian_relationships enable row level security; alter table public.announcements enable row level security; alter table public.notifications enable row level security;

do $$
declare t text; tables text[] := array['migrations','users','refresh_tokens','sessions','password_reset_tokens','role_change_audits','audit_logs','students','academic_sessions','terms','school_classes','sections','student_enrollments','subjects','teacher_assignments','attendance_records','assessments','assessment_results','fee_items','invoices','invoice_lines','payments','timetable_entries','guardian_relationships','announcements','notifications'];
begin
foreach t in array tables loop
 execute format('drop policy if exists "deny_client_access" on public.%I',t);
 execute format('create policy "deny_client_access" on public.%I for all to anon, authenticated using (false) with check (false)',t);
end loop;
end $$;

insert into public.migrations(version,name) values (1,'initial_school_management_schema'),(2,'student_management'),(3,'academic_foundation'),(4,'classes_and_sections'),(5,'student_enrollment'),(6,'attendance_records'),(7,'assessments'),(8,'assessment_results'),(9,'finance'),(10,'timetable'),(11,'guardian_relationships'),(12,'notifications') on conflict(version) do nothing;
