"use client";
import {useEffect,useState} from "react";
import Link from "next/link";

type Child={student_id:string;name:string;admission_number:string;relationship:string;primary:boolean};
type Term={id:string;name:string};
type Item=Record<string,any>;
async function api(path:string){const t=localStorage.getItem("access_token");const r=await fetch("/backend"+path,{headers:{Authorization:"Bearer "+t}});const d=await r.json().catch(()=>({}));if(r.status===401)throw Error("Session expired");if(!r.ok)throw Error(d?.error?.message||"Request failed");return d}
const list=(d:any,k:string)=>Array.isArray(d)?d:d?.[k]||d?.data||[];
export default function ParentPortal(){const [sessionId,setSessionId]=useState("");const [termId,setTermId]=useState("");const[children,setChildren]=useState<Child[]>([]);const[schoolName,setSchoolName]=useState("");const[terms,setTerms]=useState<Term[]>([]);const[selected,setSelected]=useState<Child|null>(null);const[data,setData]=useState<Record<string,Item[]>>({});const[notifications,setNotifications]=useState<Item[]>([]);const[error,setError]=useState("");
useEffect(()=>{(async()=>{try{const context=await api("/academic-context");const sessions=list(context,"sessions");const session=sessions.find((x:any)=>x.status==="active")||sessions[0];const term=session?.terms?.find((x:any)=>x.status==="active")||session?.terms?.[0];setSessionId(session?.id||"");setTermId(term?.id||"");const[me,c,n]=await Promise.all([api("/me"),api("/parent/children"),api("/notifications")]);setSchoolName(me?.school_name||"");const cs=list(c,"children");setChildren(cs);setSelected(cs[0]||null);setNotifications(list(n,"notifications"))}catch(e:any){setError(e.message||"Unable to load parent portal")}})()},[]);
useEffect(()=>{if(!selected||!sessionId||!termId)return;(async()=>{try{const id=selected.student_id;const t=await api("/parent/terms?student_id="+id+"&academic_session_id="+sessionId);setTerms(list(t,"terms"));const [a,tt,i,p]=await Promise.all([api("/parent/children/"+id+"/attendance?academic_session_id="+sessionId+"&term_id="+termId),api("/parent/children/"+id+"/timetable?academic_session_id="+sessionId+"&term_id="+termId),api("/parent/children/"+id+"/invoices?academic_session_id="+sessionId+"&term_id="+termId),api("/parent/children/"+id+"/payments?academic_session_id="+sessionId+"&term_id="+termId)]);setData({attendance:list(a,"attendance"),timetable:list(tt,"timetable"),invoices:list(i,"invoices"),payments:list(p,"payments")})}catch(e:any){setError(e.message||"Unable to load child data")}})()},[selected,sessionId,termId]);
return <div className="content standalone"><Link className="back" href="/dashboard">← Dashboard</Link><Link className="back" href="/dashboard/notifications">Notifications ({notifications.filter(n=>!n.read).length} unread)</Link><header className="topbar"><div><p className="eyebrow">PARENT PORTAL</p><h1>Family overview</h1><p className="muted">{schoolName||"Your school"} · View your linked children's school information.</p></div></header>{error&&<div className="error banner">{error}</div>}
<section className="stats"><Stat label="Children" value={children.length}/><Stat label="Attendance records" value={data.attendance?.length||0}/><Stat label="Invoices" value={data.invoices?.length||0}/><Stat label="Payments" value={data.payments?.length||0}/></section>
<section className="panel"><div className="panel-head"><div><h2>My children</h2><p>Only students linked to your guardian account.</p></div></div><div className="module-grid">{children.map(c=><button className="module" key={c.student_id} onClick={()=>setSelected(c)}><div className="module-icon">{c.name?.[0]||"S"}</div><div><strong>{c.name}</strong><p>{c.admission_number} · {c.relationship}</p></div><span>{selected?.student_id===c.student_id?"Selected":"View"}</span></button>)}</div>{!children.length&&<div className="empty">No children are linked to this account.</div>}</section>
{selected&&<><section className="panel"><div className="panel-head"><div><h2>Notifications</h2><p>School announcements and operational alerts.</p></div><Link href="/dashboard/notifications">Open notification center →</Link></div>{notifications.slice(0,5).map(n=><article className="module" key={n.id}><div className="module-icon">!</div><div><strong>{n.title}</strong><p>{n.body}</p><small>{n.category} · {n.read?"Read":"Unread"}</small></div></article>)}{!notifications.length&&<div className="empty">No notifications.</div>}</section><section className="grid-2"><Panel title="Attendance" text="Recent attendance for the selected child."><Table rows={data.attendance||[]} cols={["date","status","remarks"]}/></Panel><Panel title="Invoices" text="Current billing records."><Table rows={data.invoices||[]} cols={["invoice_number","total_amount","paid_amount","balance","status"]}/></Panel></section><section className="grid-2"><Panel title="Timetable" text="Current class timetable."><Table rows={data.timetable||[]} cols={["day_of_week","start_time","end_time","room"]}/></Panel><Panel title="Payments" text="Recorded payment history."><Table rows={data.payments||[]} cols={["amount","provider","reference","status"]}/></Panel></section><section className="panel"><div className="panel-head"><div><h2>Report cards</h2><p>Select a term to open the child's report card.</p></div></div><div className="module-grid">{terms.map(t=><Link className="module" key={t.id} href={"/dashboard/parent/report-card?studentId="+selected.student_id+"&termId="+t.id+"&sessionId="+sessionId}><div className="module-icon">R</div><div><strong>{t.name}</strong><p>View report card</p></div><span>Open</span></Link>)}</div></section></>}</div>}
function Stat({label,value}:{label:string;value:number}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
function Panel(p:{title:string;text:string;children:React.ReactNode}){return <section className="panel"><div className="panel-head"><div><h2>{p.title}</h2><p>{p.text}</p></div></div>{p.children}</section>}
function Table({rows,cols}:{rows:Item[];cols:string[]}){return <div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((x,i)=><tr key={x.id||i}>{cols.map(c=><td key={c}>{String(x[c]??"—")}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty">No records.</div>}</div>}