package service
import("errors";"strings";"time";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/repository";"gorm.io/gorm")
var(ErrAcademicSessionNotFound=errors.New("academic session not found");ErrTermNotFound=errors.New("term not found");ErrAcademicDateRange=errors.New("invalid academic date range");ErrAcademicDuplicate=errors.New("academic record already exists or invalid");ErrAcademicOverlap=errors.New("academic date range overlaps another record");ErrAcademicParentNotFound=errors.New("academic session not found"))
type AcademicService struct{sessions repository.AcademicSessionRepository;terms repository.TermRepository;db *gorm.DB}
func NewAcademicService(s repository.AcademicSessionRepository,t repository.TermRepository,db *gorm.DB)*AcademicService{return &AcademicService{s,t,db}}
func(s *AcademicService)DB()*gorm.DB{return s.db}
func validRange(a,b time.Time)bool{return !a.IsZero()&&!b.IsZero()&&!b.Before(a)}
func(s *AcademicService)CreateSession(schoolID uuid.UUID,v models.AcademicSession)(models.AcademicSession,error){v.Name=strings.TrimSpace(v.Name);if !validRange(v.StartDate,v.EndDate){return v,ErrAcademicDateRange};var x models.AcademicSession;if e:=s.db.Where("school_id = ? AND name = ?",schoolID,v.Name).First(&x).Error;e==nil{return v,ErrAcademicDuplicate}else if !errors.Is(e,gorm.ErrRecordNotFound){return v,e};if v.Status==""{v.Status=models.AcademicStatusPlanned};if v.Status==models.AcademicStatusActive{if e:=s.db.Model(&models.AcademicSession{}).Where("school_id = ? AND status = ?",schoolID,models.AcademicStatusActive).Update("status",models.AcademicStatusClosed).Error;e!=nil{return v,e}};return s.sessions.Create(schoolID,v)}
func(s *AcademicService)GetSessions(schoolID uuid.UUID)([]models.AcademicSession,error){return s.sessions.GetAll(schoolID)}
func(s *AcademicService)GetSession(schoolID,id uuid.UUID)(models.AcademicSession,error){v,e:=s.sessions.GetByID(schoolID,id);if errors.Is(e,gorm.ErrRecordNotFound){return v,ErrAcademicSessionNotFound};return v,e}
func(s *AcademicService)UpdateSession(schoolID uuid.UUID,v models.AcademicSession)error{old,e:=s.GetSession(schoolID,v.ID);if e!=nil{return e};if !validRange(v.StartDate,v.EndDate){return ErrAcademicDateRange};if v.Name!=old.Name{var x models.AcademicSession;if e=s.db.Where("school_id = ? AND name = ? AND id <> ?",schoolID,v.Name,v.ID).First(&x).Error;e==nil{return ErrAcademicDuplicate}else if !errors.Is(e,gorm.ErrRecordNotFound){return e}};if v.Status==models.AcademicStatusActive{if e=s.db.Model(&models.AcademicSession{}).Where("school_id = ? AND id <> ? AND status = ?",schoolID,v.ID,models.AcademicStatusActive).Update("status",models.AcademicStatusClosed).Error;e!=nil{return e}};return s.sessions.Update(schoolID,v)}
func(s *AcademicService)DeleteSession(schoolID,id uuid.UUID)error{if _,e:=s.GetSession(schoolID,id);e!=nil{return e};return s.sessions.Delete(schoolID,id)}
func(s *AcademicService)CreateTerm(schoolID uuid.UUID,v models.Term)(models.Term,error){v.Name=strings.ToLower(strings.TrimSpace(v.Name));if v.Name!=models.TermFirst&&v.Name!=models.TermSecond&&v.Name!=models.TermThird{return v,ErrAcademicDuplicate};if !validRange(v.StartDate,v.EndDate){return v,ErrAcademicDateRange};session,e:=s.GetSession(schoolID,v.AcademicSessionID);if e!=nil{return v,ErrAcademicParentNotFound};if v.StartDate.Before(session.StartDate)||v.EndDate.After(session.EndDate){return v,ErrAcademicDateRange};var x models.Term;if e=s.db.Where("school_id = ? AND academic_session_id = ? AND name = ?",schoolID,v.AcademicSessionID,v.Name).First(&x).Error;e==nil{return v,ErrAcademicDuplicate}else if !errors.Is(e,gorm.ErrRecordNotFound){return v,e};if e=s.db.Where("school_id = ? AND academic_session_id = ? AND start_date <= ? AND end_date >= ?",schoolID,v.AcademicSessionID,v.EndDate,v.StartDate).First(&x).Error;e==nil{return v,ErrAcademicOverlap}else if !errors.Is(e,gorm.ErrRecordNotFound){return v,e};if v.Status==models.AcademicStatusActive{if e=s.db.Model(&models.Term{}).Where("school_id = ? AND academic_session_id = ? AND status = ?",schoolID,v.AcademicSessionID,models.AcademicStatusActive).Update("status",models.AcademicStatusClosed).Error;e!=nil{return v,e}};return s.terms.Create(schoolID,v)}
func(s *AcademicService)GetTerms(schoolID,id uuid.UUID)([]models.Term,error){if _,e:=s.GetSession(schoolID,id);e!=nil{return nil,e};return s.terms.GetAll(schoolID,id)}
func(s *AcademicService)GetTerm(schoolID,id uuid.UUID)(models.Term,error){v,e:=s.terms.GetByID(schoolID,id);if errors.Is(e,gorm.ErrRecordNotFound){return v,ErrTermNotFound};return v,e}
func(s *AcademicService)UpdateTerm(schoolID uuid.UUID,v models.Term)error{old,e:=s.GetTerm(schoolID,v.ID);if e!=nil{return e};if !validRange(v.StartDate,v.EndDate)||v.AcademicSessionID!=old.AcademicSessionID{return ErrAcademicDateRange};if v.Name!=models.TermFirst&&v.Name!=models.TermSecond&&v.Name!=models.TermThird{return ErrAcademicDuplicate};var x models.Term;if e=s.db.Where("school_id = ? AND academic_session_id = ? AND id <> ? AND start_date <= ? AND end_date >= ?",schoolID,v.AcademicSessionID,v.ID,v.EndDate,v.StartDate).First(&x).Error;e==nil{return ErrAcademicOverlap}else if !errors.Is(e,gorm.ErrRecordNotFound){return e};if v.Status==models.AcademicStatusActive{if e=s.db.Model(&models.Term{}).Where("school_id = ? AND academic_session_id = ? AND id <> ? AND status = ?",schoolID,v.AcademicSessionID,v.ID,models.AcademicStatusActive).Update("status",models.AcademicStatusClosed).Error;e!=nil{return e}};return s.terms.Update(schoolID,v)}
func(s *AcademicService)DeleteTerm(schoolID,id uuid.UUID)error{if _,e:=s.GetTerm(schoolID,id);e!=nil{return e};return s.terms.Delete(schoolID,id)}
