package service
import("errors";"strings";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/repository";"gorm.io/gorm")
var(ErrClassNotFound=errors.New("class not found");ErrSectionNotFound=errors.New("section not found");ErrClassDuplicate=errors.New("class already exists");ErrSectionDuplicate=errors.New("section already exists");ErrClassInvalidLevel=errors.New("class level must be zero or greater");ErrSectionSchoolMismatch=errors.New("section belongs to another school"))
type ClassService struct{classes repository.ClassRepository;sections repository.SectionRepository;db *gorm.DB}
func NewClassService(c repository.ClassRepository,s repository.SectionRepository,db *gorm.DB)*ClassService{return &ClassService{c,s,db}}
func(s *ClassService)DB()*gorm.DB{return s.db}
func(s *ClassService)CreateClass(schoolID uuid.UUID,v models.SchoolClass)(models.SchoolClass,error){v.Name=strings.TrimSpace(v.Name);if v.Name==""||v.Level<0{return v,ErrClassInvalidLevel};var x models.SchoolClass;if e:=s.db.Where("school_id = ? AND name = ?",schoolID,v.Name).First(&x).Error;e==nil{return v,ErrClassDuplicate}else if !errors.Is(e,gorm.ErrRecordNotFound){return v,e};return s.classes.Create(schoolID,v)}
func(s *ClassService)ListClasses(schoolID uuid.UUID)([]models.SchoolClass,error){return s.classes.List(schoolID)}
func(s *ClassService)GetClass(schoolID,id uuid.UUID)(models.SchoolClass,error){v,e:=s.classes.Get(schoolID,id);if errors.Is(e,gorm.ErrRecordNotFound){return v,ErrClassNotFound};return v,e}
func(s *ClassService)UpdateClass(schoolID uuid.UUID,v models.SchoolClass)error{old,e:=s.GetClass(schoolID,v.ID);if e!=nil{return e};v.Name=strings.TrimSpace(v.Name);if v.Name==""||v.Level<0{return ErrClassInvalidLevel};if !strings.EqualFold(v.Name,old.Name){var x models.SchoolClass;if e=s.db.Where("school_id = ? AND name = ? AND id <> ?",schoolID,v.Name,v.ID).First(&x).Error;e==nil{return ErrClassDuplicate}else if !errors.Is(e,gorm.ErrRecordNotFound){return e}};return s.classes.Update(schoolID,v)}
func(s *ClassService)DeleteClass(schoolID,id uuid.UUID)error{if _,e:=s.GetClass(schoolID,id);e!=nil{return e};return s.classes.Delete(schoolID,id)}
func(s *ClassService)CreateSection(schoolID uuid.UUID,v models.Section)(models.Section,error){if _,e:=s.GetClass(schoolID,v.ClassID);e!=nil{return v,ErrClassNotFound};v.Name=strings.TrimSpace(v.Name);if v.Name==""{return v,ErrSectionDuplicate};var x models.Section;if e:=s.db.Where("school_id = ? AND class_id = ? AND name = ?",schoolID,v.ClassID,v.Name).First(&x).Error;e==nil{return v,ErrSectionDuplicate}else if !errors.Is(e,gorm.ErrRecordNotFound){return v,e};return s.sections.Create(schoolID,v)}
func(s *ClassService)ListSections(schoolID,classID uuid.UUID)([]models.Section,error){if _,e:=s.GetClass(schoolID,classID);e!=nil{return nil,e};return s.sections.List(schoolID,classID)}
func(s *ClassService)GetSection(schoolID,id uuid.UUID)(models.Section,error){v,e:=s.sections.Get(schoolID,id);if errors.Is(e,gorm.ErrRecordNotFound){return v,ErrSectionNotFound};return v,e}
func(s *ClassService)UpdateSection(schoolID uuid.UUID,v models.Section)error{old,e:=s.GetSection(schoolID,v.ID);if e!=nil{return e};if _,e=s.GetClass(schoolID,v.ClassID);e!=nil{return ErrClassNotFound};v.Name=strings.TrimSpace(v.Name);if v.Name==""{return ErrSectionDuplicate};if v.ClassID!=old.ClassID{return ErrSectionDuplicate};var x models.Section;if e=s.db.Where("school_id = ? AND class_id = ? AND name = ? AND id <> ?",schoolID,v.ClassID,v.Name,v.ID).First(&x).Error;e==nil{return ErrSectionDuplicate}else if !errors.Is(e,gorm.ErrRecordNotFound){return e};return s.sections.Update(schoolID,v)}
func(s *ClassService)DeleteSection(schoolID,id uuid.UUID)error{if _,e:=s.GetSection(schoolID,id);e!=nil{return e};return s.sections.Delete(schoolID,id)}
