package service

import("errors";"strings";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/authz";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/repository";"gorm.io/gorm")
var(ErrGuardianInvalid=errors.New("invalid guardian relationship");ErrGuardianForbidden=errors.New("guardian is not linked to student"))
type GuardianService struct{repo repository.GuardianRepository;db *gorm.DB}
func NewGuardianService(r repository.GuardianRepository,db *gorm.DB)*GuardianService{return &GuardianService{repo:r,db:db}}
func(s *GuardianService)DB()*gorm.DB{return s.db}
type GuardianChild struct{StudentID uuid.UUID `json:"student_id"`;Name string `json:"name"`;AdmissionNumber string `json:"admission_number"`;Relationship string `json:"relationship"`;Primary bool `json:"primary"`}
type GuardianTerm struct{ID uuid.UUID `json:"id"`;Name string `json:"name"`;AcademicSessionID uuid.UUID `json:"academic_session_id"`;StartDate string `json:"start_date"`;EndDate string `json:"end_date"`}
func(s *GuardianService)authorize(schoolID,gid,sid uuid.UUID)error{_,e:=s.repo.Find(schoolID,gid,sid);if errors.Is(e,gorm.ErrRecordNotFound){return ErrGuardianForbidden};return e}
func(s *GuardianService)Children(schoolID,gid uuid.UUID)([]GuardianChild,error){rels,e:=s.repo.ListByGuardian(schoolID,gid);if e!=nil{return nil,e};out:=make([]GuardianChild,0,len(rels));for _,rel:=range rels{var st models.Student;if e=s.db.Where("id=? AND school_id=?",rel.StudentID,schoolID).Preload("User").First(&st).Error;e!=nil{continue};out=append(out,GuardianChild{st.ID,st.User.Name,st.AdmissionNumber,rel.Relationship,rel.Primary})};return out,nil}
func(s *GuardianService)Terms(schoolID,gid,sid,sessionID uuid.UUID)([]GuardianTerm,error){if e:=s.authorize(schoolID,gid,sid);e!=nil{return nil,e};rels,e:=s.repo.ListByGuardian(schoolID,gid);if e!=nil||len(rels)==0{return []GuardianTerm{},e};var enr models.StudentEnrollment;if e=s.db.Where("school_id=? AND student_id=? AND academic_session_id=?",schoolID,sid,sessionID).First(&enr).Error;e!=nil{return nil,ErrGuardianInvalid};var terms []models.Term;if e=s.db.Where("school_id=? AND academic_session_id=?",schoolID,enr.AcademicSessionID).Order("start_date").Find(&terms).Error;e!=nil{return nil,e};out:=make([]GuardianTerm,0,len(terms));for _,t:=range terms{out=append(out,GuardianTerm{t.ID,t.Name,t.AcademicSessionID,t.StartDate.Format("2006-01-02"),t.EndDate.Format("2006-01-02")})};return out,nil}
func(s *GuardianService)enrollmentForStudent(schoolID,sid,sessionID uuid.UUID)(models.StudentEnrollment,error){var e models.StudentEnrollment;err:=s.db.Where("school_id=? AND student_id=? AND academic_session_id=? AND status=?",schoolID,sid,sessionID,models.EnrollmentStatusActive).First(&e).Error;return e,err}
func(s *GuardianService)Attendance(schoolID,gid,sid,sessionID,termID uuid.UUID)([]models.AttendanceRecord,error){if e:=s.authorize(schoolID,gid,sid);e!=nil{return nil,e};enr,e:=s.enrollmentForStudent(schoolID,sid,sessionID);if e!=nil{return nil,ErrGuardianInvalid};var out []models.AttendanceRecord;e=s.db.Where("school_id=? AND enrollment_id=? AND term_id=?",schoolID,enr.ID,termID).Order("date DESC").Find(&out).Error;return out,e}
func(s *GuardianService)ReportCard(schoolID,gid,sid,sessionID,tid uuid.UUID)(ReportCard,error){if e:=s.authorize(schoolID,gid,sid);e!=nil{return ReportCard{},e};var t models.Term;if e:=s.db.Where("id=? AND school_id=? AND academic_session_id=?",tid,schoolID,sessionID).First(&t).Error;e!=nil{return ReportCard{},ErrGuardianInvalid};var enr models.StudentEnrollment;if e:=s.db.Where("school_id=? AND student_id=? AND academic_session_id=? AND status<>?",schoolID,sid,t.AcademicSessionID,models.EnrollmentStatusWithdrawn).Order("created_at DESC").First(&enr).Error;e!=nil{return ReportCard{},ErrGuardianInvalid};svc:=NewAssessmentResultService(nil,s.db);return svc.ReportCardForSchool(schoolID,enr.ID,tid)}
func(s *GuardianService)Timetable(schoolID,gid,sid,sessionID,termID uuid.UUID)([]models.TimetableEntry,error){if e:=s.authorize(schoolID,gid,sid);e!=nil{return nil,e};enr,e:=s.enrollmentForStudent(schoolID,sid,sessionID);if e!=nil{return nil,ErrGuardianInvalid};var out []models.TimetableEntry;q:=s.db.Where("school_id=? AND academic_session_id=? AND term_id=? AND class_id=? AND active=?",schoolID,enr.AcademicSessionID,termID,enr.ClassID,true);if enr.SectionID!=uuid.Nil{q=q.Where("section_id IS NULL OR section_id=?",enr.SectionID)};e=q.Order("day_of_week,start_time").Find(&out).Error;return out,e}
func(s *GuardianService)Invoices(schoolID,gid,sid,sessionID,termID uuid.UUID)([]models.Invoice,error){if e:=s.authorize(schoolID,gid,sid);e!=nil{return nil,e};enr,e:=s.enrollmentForStudent(schoolID,sid,sessionID);if e!=nil{return nil,ErrGuardianInvalid};var out []models.Invoice;e=s.db.Where("school_id=? AND student_enrollment_id=? AND term_id=?",schoolID,enr.ID,termID).Order("created_at DESC").Find(&out).Error;return out,e}
func(s *GuardianService)Payments(schoolID,gid,sid,sessionID,termID uuid.UUID)([]models.Payment,error){if e:=s.authorize(schoolID,gid,sid);e!=nil{return nil,e};enr,e:=s.enrollmentForStudent(schoolID,sid,sessionID);if e!=nil{return nil,ErrGuardianInvalid};var ids []uuid.UUID;s.db.Model(&models.Invoice{}).Where("school_id=? AND student_enrollment_id=? AND term_id=?",schoolID,enr.ID,termID).Pluck("id",&ids);if len(ids)==0{return []models.Payment{},nil};var out []models.Payment;e=s.db.Where("school_id=? AND invoice_id IN ?",schoolID,ids).Order("created_at DESC").Find(&out).Error;return out,e}
func(s *GuardianService)CreateLink(schoolID,gid,sid uuid.UUID,relationship string,primary bool)(models.GuardianRelationship,error){relationship=strings.TrimSpace(relationship);if relationship==""||len(relationship)>40{return models.GuardianRelationship{},ErrGuardianInvalid};var u models.User;if e:=s.db.Where("id=? AND school_id=?",gid,schoolID).First(&u).Error;e!=nil||u.Role!=authz.RoleParent||!u.Active{return models.GuardianRelationship{},ErrGuardianInvalid};var st models.Student;if e:=s.db.Where("id=? AND school_id=?",sid,schoolID).First(&st).Error;e!=nil{return models.GuardianRelationship{},ErrGuardianInvalid};if _,e:=s.repo.Find(schoolID,gid,sid);e==nil{return models.GuardianRelationship{},ErrGuardianInvalid};return s.repo.Create(schoolID,models.GuardianRelationship{GuardianUserID:gid,StudentID:sid,Relationship:relationship,Primary:primary,Active:true})}
