package service

import("errors";"strings";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/authz";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/repository";"gorm.io/gorm")
var(ErrGuardianInvalid=errors.New("invalid guardian relationship");ErrGuardianForbidden=errors.New("guardian is not linked to student"))
type GuardianService struct{repo repository.GuardianRepository;db *gorm.DB}
func NewGuardianService(r repository.GuardianRepository,db *gorm.DB)*GuardianService{return &GuardianService{repo:r,db:db}}
func(s *GuardianService)DB()*gorm.DB{return s.db}
type GuardianChild struct{StudentID uuid.UUID `json:"student_id"`;Name string `json:"name"`;AdmissionNumber string `json:"admission_number"`;Relationship string `json:"relationship"`;Primary bool `json:"primary"`}
type GuardianTerm struct{ID uuid.UUID `json:"id"`;Name string `json:"name"`;AcademicSessionID uuid.UUID `json:"academic_session_id"`;StartDate string `json:"start_date"`;EndDate string `json:"end_date"`}
func(s *GuardianService)authorize(gid,sid uuid.UUID)error{_,e:=s.repo.Find(gid,sid);if errors.Is(e,gorm.ErrRecordNotFound){return ErrGuardianForbidden};return e}
func(s *GuardianService)Children(gid uuid.UUID)([]GuardianChild,error){rels,e:=s.repo.ListByGuardian(gid);if e!=nil{return nil,e};out:=make([]GuardianChild,0,len(rels));for _,rel:=range rels{var st models.Student;if e=s.db.Preload("User").First(&st,"id=?",rel.StudentID).Error;e!=nil{continue};out=append(out,GuardianChild{st.ID,st.User.Name,st.AdmissionNumber,rel.Relationship,rel.Primary})};return out,nil}
func(s *GuardianService)Terms(gid uuid.UUID)([]GuardianTerm,error){rels,e:=s.repo.ListByGuardian(gid);if e!=nil||len(rels)==0{return []GuardianTerm{},e};var enr models.StudentEnrollment;if e=s.db.Where("student_id=?",rels[0].StudentID).Order("created_at DESC").First(&enr).Error;e!=nil{return nil,ErrGuardianInvalid};var terms []models.Term;if e=s.db.Where("academic_session_id=?",enr.AcademicSessionID).Order("start_date").Find(&terms).Error;e!=nil{return nil,e};out:=make([]GuardianTerm,0,len(terms));for _,t:=range terms{out=append(out,GuardianTerm{t.ID,t.Name,t.AcademicSessionID,t.StartDate.Format("2006-01-02"),t.EndDate.Format("2006-01-02")})};return out,nil}
func(s *GuardianService)enrollmentForStudent(sid uuid.UUID)(models.StudentEnrollment,error){var e models.StudentEnrollment;err:=s.db.Where("student_id=? AND status=?",sid,models.EnrollmentStatusActive).Order("created_at DESC").First(&e).Error;return e,err}
func(s *GuardianService)Attendance(gid,sid uuid.UUID)([]models.AttendanceRecord,error){if e:=s.authorize(gid,sid);e!=nil{return nil,e};enr,e:=s.enrollmentForStudent(sid);if e!=nil{return nil,ErrGuardianInvalid};var out []models.AttendanceRecord;e=s.db.Where("enrollment_id=?",enr.ID).Order("date DESC").Find(&out).Error;return out,e}
func(s *GuardianService)ReportCard(gid,sid,tid uuid.UUID)(models.ReportCard,error){if e:=s.authorize(gid,sid);e!=nil{return models.ReportCard{},e};var t models.Term;if e:=s.db.First(&t,"id=?",tid).Error;e!=nil{return models.ReportCard{},ErrGuardianInvalid};var enr models.StudentEnrollment;if e:=s.db.Where("student_id=? AND academic_session_id=? AND status<>?",sid,t.AcademicSessionID,models.EnrollmentStatusWithdrawn).Order("created_at DESC").First(&enr).Error;e!=nil{return models.ReportCard{},ErrGuardianInvalid};svc:=NewAssessmentResultService(nil,s.db);return svc.ReportCard(enr.ID,tid)}
func(s *GuardianService)Timetable(gid,sid uuid.UUID)([]models.TimetableEntry,error){if e:=s.authorize(gid,sid);e!=nil{return nil,e};enr,e:=s.enrollmentForStudent(sid);if e!=nil{return nil,ErrGuardianInvalid};var out []models.TimetableEntry;q:=s.db.Where("academic_session_id=? AND class_id=? AND active=?",enr.AcademicSessionID,enr.ClassID,true);if enr.SectionID!=uuid.Nil{q=q.Where("section_id IS NULL OR section_id=?",enr.SectionID)};e=q.Order("day_of_week,start_time").Find(&out).Error;return out,e}
func(s *GuardianService)Invoices(gid,sid uuid.UUID)([]models.Invoice,error){if e:=s.authorize(gid,sid);e!=nil{return nil,e};enr,e:=s.enrollmentForStudent(sid);if e!=nil{return nil,ErrGuardianInvalid};var out []models.Invoice;e=s.db.Where("student_enrollment_id=?",enr.ID).Order("created_at DESC").Find(&out).Error;return out,e}
func(s *GuardianService)Payments(gid,sid uuid.UUID)([]models.Payment,error){if e:=s.authorize(gid,sid);e!=nil{return nil,e};enr,e:=s.enrollmentForStudent(sid);if e!=nil{return nil,ErrGuardianInvalid};var ids []uuid.UUID;s.db.Model(&models.Invoice{}).Where("student_enrollment_id=?",enr.ID).Pluck("id",&ids);if len(ids)==0{return []models.Payment{},nil};var out []models.Payment;e=s.db.Where("invoice_id IN ?",ids).Order("created_at DESC").Find(&out).Error;return out,e}
func(s *GuardianService)CreateLink(gid,sid uuid.UUID,relationship string,primary bool)(models.GuardianRelationship,error){relationship=strings.TrimSpace(relationship);if relationship==""||len(relationship)>40{return models.GuardianRelationship{},ErrGuardianInvalid};var u models.User;if e:=s.db.First(&u,"id=?",gid).Error;e!=nil||u.Role!=authz.RoleParent||!u.Active{return models.GuardianRelationship{},ErrGuardianInvalid};var st models.Student;if e:=s.db.First(&st,"id=?",sid).Error;e!=nil{return models.GuardianRelationship{},ErrGuardianInvalid};if _,e:=s.repo.Find(gid,sid);e==nil{return models.GuardianRelationship{},ErrGuardianInvalid};return s.repo.Create(models.GuardianRelationship{GuardianUserID:gid,StudentID:sid,Relationship:relationship,Primary:primary,Active:true})}
