package service

import("errors";"testing";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/authz";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/repository";"gorm.io/driver/sqlite";"gorm.io/gorm")
func TestGuardianRelationshipAccessAndSchoolIsolation(t *testing.T){
 db,err:=gorm.Open(sqlite.Open("file:guardian_test?mode=memory&cache=shared"),&gorm.Config{});if err!=nil{t.Fatal(err)}
 if err=db.AutoMigrate(&models.School{},&models.User{},&models.Student{},&models.AcademicSession{},&models.Term{},&models.SchoolClass{},&models.Section{},&models.StudentEnrollment{},&models.AttendanceRecord{},&models.Assessment{},&models.AssessmentResult{},&models.TeacherAssignment{},&models.Subject{},&models.TimetableEntry{},&models.Invoice{},&models.InvoiceLine{},&models.Payment{},&models.GuardianRelationship{});err!=nil{t.Fatal(err)}
 a:=models.School{Name:"School A",Code:"GA"};b:=models.School{Name:"School B",Code:"GB"};if err=db.Create(&a).Error;err!=nil{t.Fatal(err)};if err=db.Create(&b).Error;err!=nil{t.Fatal(err)}
 parentA:=models.User{Name:"Parent A",Email:"parent-a@test",Role:authz.RoleParent,Active:true,SchoolID:&a.ID};parentB:=models.User{Name:"Parent B",Email:"parent-b@test",Role:authz.RoleParent,Active:true,SchoolID:&b.ID};studentUser:=models.User{Name:"Student A",Email:"student-a@test",Role:authz.RoleStudent,Active:true,SchoolID:&a.ID}
 for _,u:=range []*models.User{&parentA,&parentB,&studentUser}{if err=db.Create(u).Error;err!=nil{t.Fatal(err)}}
 student:=models.Student{SchoolID:a.ID,UserID:studentUser.ID,AdmissionNumber:"ADM-A"};if err=db.Create(&student).Error;err!=nil{t.Fatal(err)}
 rel:=repository.NewGuardianRepository(db);if _,err=rel.Create(a.ID,models.GuardianRelationship{GuardianUserID:parentA.ID,StudentID:student.ID,Relationship:"mother",Active:true});err!=nil{t.Fatal(err)}
 svc:=NewGuardianService(rel,db)
 children,err:=svc.Children(a.ID,parentA.ID);if err!=nil||len(children)!=1{t.Fatalf("expected one child, err=%v len=%d",err,len(children))}
 if _,err=svc.Attendance(b.ID,parentB.ID,student.ID,uuid.Nil,uuid.Nil);err!=ErrGuardianForbidden{t.Fatalf("expected cross-school access to be forbidden, got %v",err)}
 if _,err=svc.CreateLink(b.ID,parentB.ID,student.ID,"father",false);err!=ErrGuardianInvalid{t.Fatalf("expected cross-school link rejection, got %v",err)}
 if _,err=svc.CreateLink(a.ID,parentA.ID,student.ID,"father",false);err!=ErrGuardianInvalid{t.Fatalf("expected duplicate link rejection, got %v",err)}
 if _,err=rel.Find(b.ID,parentA.ID,student.ID);!errors.Is(err,gorm.ErrRecordNotFound){t.Fatalf("expected school-scoped repository lookup to miss, got %v",err)}
}

func TestGuardianLinkLifecycleAndPrimarySemantics(t *testing.T){db,err:=gorm.Open(sqlite.Open("file:guardian_lifecycle?mode=memory&cache=shared"),&gorm.Config{});if err!=nil{t.Fatal(err)};if err=db.AutoMigrate(&models.School{},&models.User{},&models.Student{},&models.GuardianRelationship{});err!=nil{t.Fatal(err)};school:=models.School{Name:"School",Code:"GL"};if err=db.Create(&school).Error;err!=nil{t.Fatal(err)};p1:=models.User{Name:"P1",Email:"p1@test",Role:authz.RoleParent,Active:true,SchoolID:&school.ID};p2:=models.User{Name:"P2",Email:"p2@test",Role:authz.RoleParent,Active:true,SchoolID:&school.ID};su:=models.User{Name:"S",Email:"s@test",Role:authz.RoleStudent,Active:true,SchoolID:&school.ID};for _,u:=range []*models.User{&p1,&p2,&su}{if err=db.Create(u).Error;err!=nil{t.Fatal(err)}};st:=models.Student{SchoolID:school.ID,UserID:su.ID,AdmissionNumber:"ADM"};if err=db.Create(&st).Error;err!=nil{t.Fatal(err)};repo:=repository.NewGuardianRepository(db);svc:=NewGuardianService(repo,db);l1,e:=svc.CreateLink(school.ID,p1.ID,st.ID,"mother",true);if e!=nil{t.Fatal(e)};l2,e:=svc.CreateLink(school.ID,p2.ID,st.ID,"father",true);if e!=nil{t.Fatal(e)};var old models.GuardianRelationship;if err=db.First(&old,"id=?",l1.ID).Error;err!=nil{t.Fatal(err)};if old.Primary{t.Fatal("expected previous primary to be demoted")};if !l2.Primary{t.Fatal("expected new primary")};if e=svc.DeactivateLink(school.ID,l2.ID);e!=nil{t.Fatal(e)};if _,e=svc.authorize(school.ID,p2.ID,st.ID);e!=ErrGuardianForbidden{t.Fatalf("expected deactivated link forbidden, got %v",e)};if _,e=svc.ReactivateLink(school.ID,l2.ID,false);e!=nil{t.Fatal(e)};if _,e=svc.authorize(school.ID,p2.ID,st.ID);e!=nil{t.Fatalf("expected reactivated link authorized, got %v",e)};if _,e=svc.ReactivateLink(school.ID,l2.ID,true);e!=nil{t.Fatal(e)}}

func TestGuardianInactiveUserCannotAccessActiveLink(t *testing.T){db,err:=gorm.Open(sqlite.Open("file:guardian_inactive_user?mode=memory&cache=shared"),&gorm.Config{});if err!=nil{t.Fatal(err)};if err=db.AutoMigrate(&models.School{},&models.User{},&models.Student{},&models.GuardianRelationship{});err!=nil{t.Fatal(err)};school:=models.School{Name:"School",Code:"GI"};if err=db.Create(&school).Error;err!=nil{t.Fatal(err)};p:=models.User{Name:"P",Email:"pi@test",Role:authz.RoleParent,Active:true,SchoolID:&school.ID};su:=models.User{Name:"S",Email:"si@test",Role:authz.RoleStudent,Active:true,SchoolID:&school.ID};for _,u:=range []*models.User{&p,&su}{if err=db.Create(u).Error;err!=nil{t.Fatal(err)}};st:=models.Student{SchoolID:school.ID,UserID:su.ID,AdmissionNumber:"ADM-I"};if err=db.Create(&st).Error;err!=nil{t.Fatal(err)};repo:=repository.NewGuardianRepository(db);if _,err=repo.Create(school.ID,models.GuardianRelationship{GuardianUserID:p.ID,StudentID:st.ID,Relationship:"mother",Active:true});err!=nil{t.Fatal(err)};if err=db.Model(&p).Update("active",false).Error;err!=nil{t.Fatal(err)};svc:=NewGuardianService(repo,db);if _,err=svc.Children(school.ID,p.ID);err!=nil{t.Fatal(err)};if _,err=svc.authorize(school.ID,p.ID,st.ID);err!=ErrGuardianForbidden{t.Fatalf("expected inactive guardian to be forbidden, got %v",err)}}
