package service
import("errors";"strings";"time";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/repository";"gorm.io/gorm")
var(ErrNotificationInvalid=errors.New("invalid notification request");ErrNotificationNotFound=errors.New("notification not found"))
type NotificationService struct{repo repository.NotificationRepository;db *gorm.DB}
func NewNotificationService(r repository.NotificationRepository,db *gorm.DB)*NotificationService{return &NotificationService{r,db}}
func(s *NotificationService)DB()*gorm.DB{return s.db}
func(s *NotificationService)CreateAnnouncement(a models.Announcement)(models.Announcement,error){a.Title=strings.TrimSpace(a.Title);a.Body=strings.TrimSpace(a.Body);a.Category=strings.TrimSpace(a.Category);if a.Title==""||a.Body==""||len(a.Title)>180||len(a.Category)>40{return models.Announcement{},ErrNotificationInvalid};if a.Audience==models.AudienceClass&&a.ClassID==nil{return models.Announcement{},ErrNotificationInvalid};if a.Audience!=models.AudienceAll&&a.Audience!=models.AudienceParents&&a.Audience!=models.AudienceClass&&a.Audience!=models.AudienceUser{return models.Announcement{},ErrNotificationInvalid};return s.repo.CreateAnnouncement(a)}
func(s *NotificationService)Publish(id uuid.UUID)(int,error){var a models.Announcement;if e:=s.db.First(&a,"id=?",id).Error;e!=nil{return 0,ErrNotificationNotFound};if a.Published{return 0,nil};var ids []uuid.UUID;switch a.Audience{case models.AudienceAll:s.db.Model(&models.User{}).Where("active=?",true).Pluck("id",&ids);case models.AudienceParents:s.db.Model(&models.User{}).Where("role=? AND active=?","parent",true).Pluck("id",&ids);case models.AudienceUser:ids=[]uuid.UUID{a.CreatedBy};case models.AudienceClass:s.db.Table("users u").Joins("JOIN students s ON s.user_id=u.id").Joins("JOIN student_enrollments e ON e.student_id=s.id").Where("e.class_id=? AND e.status=? AND u.active=?",*a.ClassID,models.EnrollmentStatusActive,true).Pluck("u.id",&ids);var pids []uuid.UUID;s.db.Table("guardian_relationships gr").Joins("JOIN student_enrollments e ON e.student_id=gr.student_id").Where("e.class_id=? AND e.status=? AND gr.active=?",*a.ClassID,models.EnrollmentStatusActive,true).Pluck("gr.guardian_user_id",&pids);ids=append(ids,pids...)}
seen:=map[uuid.UUID]bool{};count:=0;for _,uid:=range ids{if seen[uid]{continue};seen[uid]=true;n:=models.Notification{UserID:uid,AnnouncementID:&a.ID,Title:a.Title,Body:a.Body,Category:a.Category};if e:=s.repo.CreateNotification(n);e!=nil&&!errors.Is(e,gorm.ErrDuplicatedKey){return count,e};count++};now:=time.Now();if e:=s.db.Model(&a).Updates(map[string]interface{}{"published":true,"published_at":&now}).Error;e!=nil{return count,e};return count,nil}
func(s *NotificationService)List(uid uuid.UUID)([]models.Notification,error){return s.repo.ListForUser(uid)}
func(s *NotificationService)MarkRead(uid,nid uuid.UUID)error{if e:=s.repo.MarkRead(uid,nid);e!=nil{return e};return nil}
// EventHook creates a notification immediately; delivery providers can consume pending records asynchronously.
func(s *NotificationService)EventHook(uid uuid.UUID,title,body,category string)error{if uid==uuid.Nil||strings.TrimSpace(title)==""||strings.TrimSpace(body)==""{return ErrNotificationInvalid};n:=models.Notification{UserID:uid,Title:title,Body:body,Category:category};return s.repo.CreateNotification(n).Error}
