package service
import("errors";"strings";"time";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/models";"github.com/onoja217/users-management-app/internal/repository";"gorm.io/gorm")
var(ErrNotificationInvalid=errors.New("invalid notification request");ErrNotificationNotFound=errors.New("notification not found"))
type NotificationService struct{repo repository.NotificationRepository;db *gorm.DB}
func NewNotificationService(r repository.NotificationRepository,db *gorm.DB)*NotificationService{return &NotificationService{r,db}}
func(s *NotificationService)DB()*gorm.DB{return s.db}
func(s *NotificationService)CreateAnnouncement(schoolID uuid.UUID,a models.Announcement)(models.Announcement,error){a.Title=strings.TrimSpace(a.Title);a.Body=strings.TrimSpace(a.Body);a.Category=strings.TrimSpace(a.Category);if a.Title==""||a.Body==""||len(a.Title)>180||len(a.Category)>40{return models.Announcement{},ErrNotificationInvalid};if a.Audience==models.AudienceClass&&a.ClassID==nil{return models.Announcement{},ErrNotificationInvalid};if a.Audience!=models.AudienceAll&&a.Audience!=models.AudienceTeachers&&a.Audience!=models.AudienceStudents&&a.Audience!=models.AudienceParents&&a.Audience!=models.AudienceClass{return models.Announcement{},ErrNotificationInvalid};var creator models.User;if e:=s.db.Where("id=? AND school_id=? AND active=?",a.CreatedBy,schoolID,true).First(&creator).Error;e!=nil{return models.Announcement{},ErrNotificationInvalid};a.SchoolID=schoolID;return s.repo.CreateAnnouncement(schoolID,a)}
func(s *NotificationService)Publish(schoolID,id uuid.UUID)(int,error){var a models.Announcement;if e:=s.db.Where("school_id=? AND id=?",schoolID,id).First(&a).Error;e!=nil{return 0,ErrNotificationNotFound};if a.Published{return 0,nil};var ids []uuid.UUID;switch a.Audience{case models.AudienceAll:s.db.Model(&models.User{}).Where("school_id=? AND active=?",schoolID,true).Pluck("id",&ids);case models.AudienceTeachers:s.db.Model(&models.User{}).Where("school_id=? AND role=? AND active=?",schoolID,models.RoleTeacher,true).Pluck("id",&ids);case models.AudienceStudents:s.db.Model(&models.User{}).Where("school_id=? AND role=? AND active=?",schoolID,models.RoleStudent,true).Pluck("id",&ids);case models.AudienceParents:s.db.Model(&models.User{}).Where("school_id=? AND role=? AND active=?",schoolID,models.RoleParent,true).Pluck("id",&ids);case models.AudienceClass:s.db.Table("users u").Joins("JOIN students s ON s.user_id=u.id AND s.school_id=u.school_id").Joins("JOIN student_enrollments e ON e.student_id=s.id AND e.school_id=s.school_id").Where("u.school_id=? AND s.school_id=? AND e.school_id=? AND e.class_id=? AND e.status=? AND u.active=?",schoolID,schoolID,schoolID,*a.ClassID,models.EnrollmentStatusActive,true).Pluck("u.id",&ids);var pids []uuid.UUID;s.db.Table("guardian_relationships gr").Joins("JOIN student_enrollments e ON e.student_id=gr.student_id AND e.school_id=gr.school_id").Where("gr.school_id=? AND e.school_id=? AND e.class_id=? AND e.status=? AND gr.active=?",schoolID,schoolID,schoolID,*a.ClassID,models.EnrollmentStatusActive,true).Pluck("gr.guardian_user_id",&pids);ids=append(ids,pids...)}
seen:=map[uuid.UUID]bool{};count:=0;for _,uid:=range ids{if seen[uid]{continue};seen[uid]=true;n:=models.Notification{SchoolID:schoolID,UserID:uid,AnnouncementID:&a.ID,Title:a.Title,Body:a.Body,Category:a.Category};if _,e:=s.repo.CreateNotification(schoolID,n);e!=nil&&!errors.Is(e,gorm.ErrDuplicatedKey){return count,e};count++};now:=time.Now();if e:=s.db.Model(&models.Announcement{}).Where("school_id=? AND id=?",schoolID,id).Updates(map[string]interface{}{"published":true,"published_at":&now}).Error;e!=nil{return count,e};return count,nil}
func(s *NotificationService)ListAnnouncements(schoolID uuid.UUID)([]models.Announcement,error){return s.repo.ListAnnouncements(schoolID)}
func(s *NotificationService)List(schoolID,userID uuid.UUID)([]models.Notification,error){return s.repo.ListForUser(schoolID,userID)}
func(s *NotificationService)MarkRead(schoolID,userID,nid uuid.UUID)error{return s.repo.MarkRead(schoolID,userID,nid)}
func(s *NotificationService)EventHook(schoolID,userID uuid.UUID,title,body,category string)error{if schoolID==uuid.Nil||userID==uuid.Nil||strings.TrimSpace(title)==""||strings.TrimSpace(body)==""{return ErrNotificationInvalid};n:=models.Notification{SchoolID:schoolID,UserID:userID,Title:title,Body:body,Category:category};_,e:=s.repo.CreateNotification(schoolID,n);return e}
