package service
import("errors";"strings";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/auth";"github.com/onoja217/users-management-app/internal/authz";"github.com/onoja217/users-management-app/internal/models";"gorm.io/gorm")
var(ErrOnboardingInvalidRole=errors.New("invalid school onboarding role");ErrOnboardingDuplicateEmail=errors.New("user email already exists");ErrOnboardingDuplicateAdmission=errors.New("admission number already exists");ErrOnboardingStudentExists=errors.New("student profile already exists");ErrOnboardingGuardianInvalid=errors.New("guardian relationship is invalid");ErrOnboardingGuardianLinkExists=errors.New("guardian is already linked to student");ErrOnboardingStudentNotFound=errors.New("student not found"))
type PersonOnboardingRequest struct{Name string;Email string;Password string;Role string;AdmissionNumber string;EnrollmentStatus string;StudentID uuid.UUID;Relationship string;Primary bool}
type PersonOnboardingResult struct{User models.User \`json:"user"\`;Student *models.Student \`json:"student,omitempty"\`;GuardianLink *models.GuardianRelationship \`json:"guardian_link,omitempty"\`}
type PersonOnboardingService struct{db *gorm.DB}
func NewPersonOnboardingService(db *gorm.DB)*PersonOnboardingService{return &PersonOnboardingService{db:db}}
func(s *PersonOnboardingService)DB()*gorm.DB{return s.db}
func(s *PersonOnboardingService)Onboard(schoolID uuid.UUID,req PersonOnboardingRequest)(PersonOnboardingResult,error){role:=strings.TrimSpace(req.Role);if role==""{role=authz.RoleStudent};if !authz.IsValidRole(role)||role==authz.RoleSuperAdmin||role==authz.RoleSchoolAdmin{return PersonOnboardingResult{},ErrOnboardingInvalidRole};name:=strings.TrimSpace(req.Name);email:=strings.ToLower(strings.TrimSpace(req.Email));admission:=strings.TrimSpace(req.AdmissionNumber);relationship:=strings.TrimSpace(req.Relationship);if name==""||email==""||strings.TrimSpace(req.Password)==""{return PersonOnboardingResult{},ErrOnboardingInvalidRole};if role==authz.RoleStudent&&admission==""{return PersonOnboardingResult{},ErrOnboardingDuplicateAdmission};hash,err:=auth.HashPassword(req.Password);if err!=nil{return PersonOnboardingResult{},err};var result PersonOnboardingResult;err=s.db.Transaction(func(tx *gorm.DB)error{var existing models.User;if e:=tx.Where("LOWER(email) = ?",email).First(&existing).Error;e==nil{return ErrOnboardingDuplicateEmail}else if !errors.Is(e,gorm.ErrRecordNotFound){return e};if role==authz.RoleStudent{var es models.Student;if e:=tx.Where("school_id = ? AND admission_number = ?",schoolID,admission).First(&es).Error;e==nil{return ErrOnboardingDuplicateAdmission}else if !errors.Is(e,gorm.ErrRecordNotFound){return e}};user:=models.User{Name:name,Email:email,PasswordHash:hash,Role:role,Active:true,SchoolID:&schoolID};if e:=tx.Create(&user).Error;e!=nil{if isDuplicateDBError(e){return ErrOnboardingDuplicateEmail};return e};result.User=user;if role==authz.RoleStudent{student:=models.Student{SchoolID:schoolID,UserID:user.ID,AdmissionNumber:admission,EnrollmentStatus:req.EnrollmentStatus};if e:=tx.Create(&student).Error;e!=nil{if isDuplicateDBError(e){return ErrOnboardingStudentExists};return e};result.Student=&student};if role==authz.RoleParent&&req.StudentID!=uuid.Nil{var student models.Student;if e:=tx.Where("id = ? AND school_id = ?",req.StudentID,schoolID).First(&student).Error;e!=nil{if errors.Is(e,gorm.ErrRecordNotFound){return ErrOnboardingStudentNotFound};return e};if len(relationship)==0||len(relationship)>40{return ErrOnboardingGuardianInvalid};var el models.GuardianRelationship;if e:=tx.Where("school_id = ? AND guardian_user_id = ? AND student_id = ? AND active = true",schoolID,user.ID,student.ID).First(&el).Error;e==nil{return ErrOnboardingGuardianLinkExists}else if !errors.Is(e,gorm.ErrRecordNotFound){return e};link:=models.GuardianRelationship{SchoolID:schoolID,GuardianUserID:user.ID,StudentID:student.ID,Relationship:relationship,Primary:req.Primary,Active:true};if e:=tx.Create(&link).Error;e!=nil{if isDuplicateDBError(e){return ErrOnboardingGuardianLinkExists};return e};result.GuardianLink=&link};return nil});if err!=nil{return PersonOnboardingResult{},err};return result,nil}
func isDuplicateDBError(err error)bool{if err==nil{return false};v:=strings.ToLower(err.Error());return strings.Contains(v,"unique")||strings.Contains(v,"duplicate")}
