package service
import("errors";"github.com/google/uuid";"github.com/onoja217/users-management-app/internal/models";"gorm.io/gorm")
var ErrStudentPortalForbidden=errors.New("student portal access forbidden")
var ErrStudentPortalNotFound=errors.New("student portal record not found")
type StudentPortalService struct{db *gorm.DB}
func NewStudentPortalService(db *gorm.DB)*StudentPortalService{return &StudentPortalService{db}}
type StudentPortalProfile struct{ID uuid.UUID `json:"id"`;UserID uuid.UUID `json:"user_id"`;Name string `json:"name"`;Email string `json:"email"`;AdmissionNumber string `json:"admission_number"`;Gender string `json:"gender"`;EnrollmentStatus string `json:"enrollment_status"`}
type StudentPortalEnrollment struct{ID uuid.UUID `json:"id"`;AcademicSessionID uuid.UUID `json:"academic_session_id"`;SessionName string `json:"session_name"`;ClassID uuid.UUID `json:"class_id"`;ClassName string `json:"class_name"`;SectionID uuid.UUID `json:"section_id"`;SectionName string `json:"section_name"`;Status string `json:"status"`}
func(s *StudentPortalService)student(schoolID,uid uuid.UUID)(models.Student,error){var st models.Student;if e:=s.db.Where("school_id=? AND user_id=?",schoolID,uid).First(&st).Error;e!=nil{if errors.Is(e,gorm.ErrRecordNotFound){return st,ErrStudentPortalForbidden};return st,e};return st,nil}
func(s *StudentPortalService)Profile(schoolID,uid uuid.UUID)(StudentPortalProfile,error){st,e:=s.student(schoolID,uid);if e!=nil{return StudentPortalProfile{},e};var u models.User;if e=s.db.Where("id=? AND school_id=?",st.UserID,schoolID).First(&u).Error;e!=nil{return StudentPortalProfile{},e};return StudentPortalProfile{st.ID,st.UserID,u.Name,u.Email,st.AdmissionNumber,st.Gender,st.EnrollmentStatus},nil}
func(s *StudentPortalService)Enrollment(schoolID,uid,sessionID uuid.UUID)(StudentPortalEnrollment,error){st,e:=s.student(schoolID,uid);if e!=nil{return StudentPortalEnrollment{},e};var en models.StudentEnrollment;if e=s.db.Preload("AcademicSession","school_id = ?",schoolID).Preload("SchoolClass","school_id = ?",schoolID).Preload("Section","school_id = ?",schoolID).Where("school_id=? AND student_id=? AND academic_session_id=? AND status=?",schoolID,st.ID,sessionID,models.EnrollmentStatusActive).First(&en).Error;e!=nil{return StudentPortalEnrollment{},ErrStudentPortalNotFound};return StudentPortalEnrollment{en.ID,en.AcademicSessionID,en.AcademicSession.Name,en.ClassID,en.SchoolClass.Name,en.SectionID,en.Section.Name,en.Status},nil}
func(s *StudentPortalService)Terms(schoolID,uid,sessionID uuid.UUID)([]GuardianTerm,error){en,e:=s.Enrollment(schoolID,uid,sessionID);if e!=nil{return nil,e};var terms []models.Term;if e=s.db.Where("school_id=? AND academic_session_id=?",schoolID,en.AcademicSessionID).Order("start_date").Find(&terms).Error;e!=nil{return nil,e};out:=make([]GuardianTerm,0,len(terms));for _,t:=range terms{out=append(out,GuardianTerm{t.ID,t.Name,t.AcademicSessionID,t.StartDate.Format("2006-01-02"),t.EndDate.Format("2006-01-02")})};return out,nil}
func(s *StudentPortalService)Attendance(schoolID,uid,sessionID,termID uuid.UUID)([]models.AttendanceRecord,error){st,e:=s.student(schoolID,uid);if e!=nil{return nil,e};var en models.StudentEnrollment;if e=s.db.Where("school_id=? AND student_id=? AND academic_session_id=? AND status=?",schoolID,st.ID,sessionID,models.EnrollmentStatusActive).First(&en).Error;e!=nil{return []models.AttendanceRecord{},nil};var out []models.AttendanceRecord;e=s.db.Where("school_id=? AND enrollment_id=? AND term_id=? AND term_id IN (SELECT id FROM terms WHERE school_id=? AND academic_session_id=?)",schoolID,en.ID,termID,schoolID,sessionID).Preload("Term","school_id = ?",schoolID).Order("date DESC").Find(&out).Error;return out,e}
func(s *StudentPortalService)Timetable(schoolID,uid,sessionID,termID uuid.UUID)([]models.TimetableEntry,error){en,e:=s.Enrollment(schoolID,uid,sessionID);if e!=nil{return nil,e};var out []models.TimetableEntry;e=s.db.Where("school_id=? AND academic_session_id=? AND term_id=? AND class_id=? AND active=? AND (section_id IS NULL OR section_id=?)",schoolID,en.AcademicSessionID,termID,en.ClassID,true,en.SectionID).Order("day_of_week,start_time").Find(&out).Error;return out,e}
func(s *StudentPortalService)ReportCard(schoolID,uid,sessionID,termID uuid.UUID)(ReportCard,error){en,e:=s.Enrollment(schoolID,uid,sessionID);if e!=nil{return ReportCard{},e};if en.AcademicSessionID!=sessionID{return ReportCard{},ErrStudentPortalNotFound};var t models.Term;if e=s.db.Where("school_id=? AND id=? AND academic_session_id=?",schoolID,termID,sessionID).First(&t).Error;e!=nil{return ReportCard{},ErrStudentPortalNotFound};return NewAssessmentResultService(nil,s.db).ReportCardForSchool(schoolID,en.ID,sessionID,t.ID)}
func(s *StudentPortalService)Invoices(schoolID,uid,sessionID,termID uuid.UUID)([]models.Invoice,error){en,e:=s.Enrollment(schoolID,uid,sessionID);if e!=nil{return nil,e};var out []models.Invoice;e=s.db.Where("school_id=? AND student_enrollment_id=? AND term_id=?",schoolID,en.ID,termID).Preload("Term","school_id = ?",schoolID).Order("created_at DESC").Find(&out).Error;return out,e}
func(s *StudentPortalService)Payments(schoolID,uid,sessionID,termID uuid.UUID)([]models.Payment,error){en,e:=s.Enrollment(schoolID,uid,sessionID);if e!=nil{return nil,e};var ids []uuid.UUID;s.db.Model(&models.Invoice{}).Where("school_id=? AND student_enrollment_id=? AND term_id=?",schoolID,en.ID,termID).Pluck("id",&ids);if len(ids)==0{return []models.Payment{},nil};var out []models.Payment;e=s.db.Where("school_id=? AND invoice_id IN ?",schoolID,ids).Order("created_at DESC").Find(&out).Error;return out,e}
