"use client";
import {useEffect,useState}from"react";
import Link from"next/link";
type Post={id:string;title:string;slug:string;excerpt:string;content:string;featured_image_url?:string;status:string;featured:boolean};
type Album={id:string;title:string;slug:string;description:string;cover_image_url?:string;status:string;featured:boolean};
async function api(path:string,o:RequestInit={}){const h=new Headers(o.headers);h.set("Authorization","Bearer "+localStorage.getItem("access_token"));if(!(o.body instanceof FormData))h.set("Content-Type","application/json");const r=await fetch("/backend"+path,{...o,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error?.message||d?.error||"Request failed");return d}
export default function ContentAdmin(){
 const[posts,setPosts]=useState<Post[]>([]),[albums,setAlbums]=useState<Album[]>([]),[title,setTitle]=useState(""),[excerpt,setExcerpt]=useState(""),[body,setBody]=useState(""),[postImage,setPostImage]=useState<File|null>(null),[albumTitle,setAlbumTitle]=useState(""),[albumDescription,setAlbumDescription]=useState(""),[albumImages,setAlbumImages]=useState<File[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const[a,b]=await Promise.all([api("/admin/blog/posts"),api("/admin/gallery/albums")]);setPosts(a.posts||[]);setAlbums(b.albums||[])}catch(e:any){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function createPost(){setBusy(true);setError("");try{const p=await api("/admin/blog/posts",{method:"POST",body:JSON.stringify({title,excerpt,content:body,status:"draft"})});if(postImage){const f=new FormData();f.append("image",postImage);await api("/admin/blog/posts/"+p.id+"/image",{method:"POST",body:f})}await api("/admin/blog/posts/"+p.id+"/publish",{method:"POST"});setTitle("");setExcerpt("");setBody("");setPostImage(null);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function createAlbum(){setBusy(true);setError("");try{const a=await api("/admin/gallery/albums",{method:"POST",body:JSON.stringify({title:albumTitle,description:albumDescription,status:"draft"})});let cover="";for(const file of albumImages){const f=new FormData();f.append("image",file);const image=await api("/admin/gallery/albums/"+a.id+"/images",{method:"POST",body:f});if(!cover)cover=image.image_url}if(cover)await api("/admin/gallery/albums/"+a.id,{method:"PUT",body:JSON.stringify({cover_image_url:cover})});await api("/admin/gallery/albums/"+a.id,{method:"PUT",body:JSON.stringify({status:"published"})});setAlbumTitle("");setAlbumDescription("");setAlbumImages([]);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function removePost(id:string){if(!confirm("Delete this post?"))return;try{await api("/admin/blog/posts/"+id,{method:"DELETE"});await load()}catch(e:any){setError(e.message)}}
 async function removeAlbum(id:string){if(!confirm("Delete this album and its images?"))return;try{await api("/admin/gallery/albums/"+id,{method:"DELETE"});await load()}catch(e:any){setError(e.message)}}
 return <div className="content standalone" style={{maxWidth:1200,margin:"0 auto"}}><Link className="back" href="/dashboard">← Dashboard</Link><header className="topbar"><div><p className="eyebrow">PUBLIC SCHOOL WEBSITE</p><h1>Blog & Gallery</h1><p className="muted">Publish school news and photographs to your public school homepage.</p></div></header>{error&&<div className="error banner">{error}</div>}
 <section className="panel"><div className="panel-head"><div><h2>Create blog post</h2><p>Posts are published to the school's public website after creation.</p></div></div><div className="form-grid"><label>Title<input value={title}onChange={e=>setTitle(e.target.value)}placeholder="Annual Prize Giving Day"/></label><label>Excerpt<input value={excerpt}onChange={e=>setExcerpt(e.target.value)}placeholder="Short summary"/></label><label style={{gridColumn:"1/-1"}}>Content<textarea value={body}onChange={e=>setBody(e.target.value)}rows={8}placeholder="Write the school story or announcement…"/></label><label>Featured image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setPostImage(e.target.files?.[0]||null)}/><small>PNG, JPEG or WebP; maximum 10 MB.</small></label><div className="form-action"><button disabled={busy||!title||!body}onClick={createPost}>{busy?"Publishing…":"Publish post"}</button></div></div></section>
 <section className="panel"><div className="panel-head"><div><h2>Create gallery album</h2><p>Upload multiple photographs for a school event or activity.</p></div></div><div className="form-grid"><label>Album title<input value={albumTitle}onChange={e=>setAlbumTitle(e.target.value)}placeholder="Inter-House Sports"/></label><label>Description<input value={albumDescription}onChange={e=>setAlbumDescription(e.target.value)}/></label><label style={{gridColumn:"1/-1"}}>Photographs<input type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={e=>setAlbumImages(Array.from(e.target.files||[]))}/><small>{albumImages.length} selected · maximum 10 MB each.</small></label><div className="form-action"><button disabled={busy||!albumTitle||!albumImages.length}onClick={createAlbum}>{busy?"Uploading…":"Publish album"}</button></div></div></section>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(360px,1fr))",gap:20}}><section className="panel"><h2>Published posts</h2>{posts.map(p=><div key={p.id} style={{padding:"14px 0",borderBottom:"1px solid #e5e7eb"}}><strong>{p.title}</strong><div><small>{p.status}</small> <button className="ghost" onClick={()=>removePost(p.id)}>Delete</button></div></div>)}{!posts.length&&<div className="empty">No posts yet.</div>}</section><section className="panel"><h2>Gallery albums</h2>{albums.map(a=><div key={a.id} style={{padding:"14px 0",borderBottom:"1px solid #e5e7eb"}}><strong>{a.title}</strong><div><small>{a.status}</small> <button className="ghost" onClick={()=>removeAlbum(a.id)}>Delete</button></div></div>)}{!albums.length&&<div className="empty">No albums yet.</div>}</section></div>
 </div>
}