"use client";
import{useEffect,useState}from"react";import Link from"next/link";
async function api(path:string,options:RequestInit={}){const t=localStorage.getItem("access_token");const r=await fetch("/backend"+path,{...options,headers:{...options.headers,Authorization:"Bearer "+t,"Content-Type":"application/json"}});const d=await r.json().catch(()=>({}));if(r.status===401)throw Error("Session expired");if(!r.ok)throw Error(d?.error?.message||d?.error||"Request failed");return d}
const list=(d:any,k:string)=>Array.isArray(d)?d:d?.[k]||d?.data||[];
export default function Notifications(){const[n,setN]=useState<any[]>([]),[e,setE]=useState(""),[me,setMe]=useState<any>(null),[classes,setClasses]=useState<any[]>([]),[busy,setBusy]=useState(false),[readBusy,setReadBusy]=useState(""),[form,setForm]=useState({title:"",body:"",category:"general",audience:"all",class_id:""});
const canManage=["super_admin","school_admin"].includes(me?.role);
async function load(){try{setE("");const m=await api("/me");setMe(m);const calls=[api("/notifications")];if(["super_admin","school_admin"].includes(m?.role))calls.push(api("/admin/classes"));const r=await Promise.all(calls);setN(list(r[0],"notifications"));if(r[1])setClasses(list(r[1],"classes"))}catch(x:any){setE(x.message||"Unable to load notifications")}}
useEffect(()=>{load()},[]);
async function publish(){if(!form.title.trim()||!form.body.trim()){setE("Announcement title and message are required.");return}if(form.audience==="class"&&!form.class_id){setE("Select a class for a class announcement.");return}setBusy(true);setE("");try{const payload={...form,class_id:form.audience==="class"?form.class_id:null};const a=await api("/admin/announcements",{method:"POST",body:JSON.stringify(payload)});const id=a?.id||a?.announcement?.id;if(!id)throw Error("Announcement was created but no id was returned");const result=await api("/admin/announcements/"+id+"/publish",{method:"POST"});setForm({title:"",body:"",category:"general",audience:"all",class_id:""});await load();if(result?.notifications===0)setE("Announcement published, but there are no active users in the selected audience.");}catch(x:any){setE(x.message||"Unable to publish announcement")}finally{setBusy(false)}}
async function read(id:string){setReadBusy(id);try{await api("/notifications/"+id+"/read",{method:"POST"});await load()}catch(x:any){setE(x.message||"Unable to mark notification read")}finally{setReadBusy("")}}
return <div className="content standalone"><Link className="back"href="/dashboard">← Dashboard</Link><header className="topbar"><div><p className="eyebrow">COMMUNICATION</p><h1>Notifications</h1><p className="muted">School announcements and operational alerts.</p></div></header>{e&&<div className="error banner">{e}</div>}{canManage&&<div className="panel"><div className="panel-head"><div><h2>Send announcement</h2><p>Send a school announcement directly to teachers, students, parents, or the whole school.</p></div></div><div className="form-grid"><label>Title<input value={form.title} onChange={x=>setForm({...form,title:x.target.value})} placeholder="e.g. Staff meeting"/></label><label>Category<select value={form.category} onChange={x=>setForm({...form,category:x.target.value})}><option value="general">General</option><option value="attendance">Attendance</option><option value="fees">Fees</option><option value="results">Results</option><option value="academic">Academic</option></select></label><label>Audience<select value={form.audience} onChange={x=>setForm({...form,audience:x.target.value,class_id:""})}><option value="all">Whole school</option><option value="teachers">Teachers</option><option value="students">Students</option><option value="parents">Parents</option><option value="class">Specific class (students + parents)</option></select></label>{form.audience==="class"&&<label>Class<select value={form.class_id} onChange={x=>setForm({...form,class_id:x.target.value})}><option value="">Select class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label style={{gridColumn:"1/-1"}}>Message<textarea value={form.body} onChange={x=>setForm({...form,body:x.target.value})} rows={6} placeholder="Write your announcement..."/></label><div className="form-action"><button disabled={busy} onClick={publish}>{busy?"Sending...":"Send announcement"}</button></div></div></div>}<div className="panel"><div className="panel-head"><div><h2>My notifications</h2><p>Unread state is stored per user.</p></div></div>{n.map(x=><article className="module" key={x.id}><div className="module-icon">!</div><div><strong>{x.title}</strong><p>{x.body}</p><small>{x.category} · {x.read?"Read":"Unread"}</small></div>{!x.read&&<button disabled={readBusy===x.id} onClick={()=>read(x.id)}>{readBusy===x.id?"Saving...":"Mark read"}</button>}</article>)}{!n.length&&<div className="empty">No notifications.</div>}</div></div>}
