package main

import (
    "log"
    "os"
    "github.com/gin-gonic/gin"
    "github.com/onoja217/users-management-app/internal/auth"
    "github.com/onoja217/users-management-app/internal/authz"
    "github.com/onoja217/users-management-app/internal/controller"
    "github.com/onoja217/users-management-app/internal/database"
    "github.com/onoja217/users-management-app/internal/middleware"
    "github.com/onoja217/users-management-app/internal/models"
    "github.com/onoja217/users-management-app/internal/repository"
    "github.com/onoja217/users-management-app/internal/service"
)
func main() {
    if err:=auth.ConfigureSecret(os.Getenv("JWT_SECRET"));err!=nil{log.Fatal(err)}
    db,err:=database.Connect();if err!=nil{log.Fatal(err)}
    if err:=database.Migrate(db);err!=nil{log.Fatal(err)}
    db.Model(&models.User{}).Where("role = ?","admin").Update("role",authz.RoleSuperAdmin)
    db.Model(&models.User{}).Where("role = ?","user").Update("role",authz.RoleStudent)
    var adminUser models.User
    if err:=db.Where("email = ?","admin@example.com").First(&adminUser).Error;err==nil{
        if !adminUser.Active||adminUser.Role!=authz.RoleSuperAdmin{adminUser.Role=authz.RoleSuperAdmin;adminUser.Active=true;if err:=db.Save(&adminUser).Error;err!=nil{log.Fatal("failed to configure admin user: ",err)}}
    }
    r:=gin.Default();r.SetTrustedProxies(nil)
    repo:=repository.NewUserRepository(db);svc:=service.NewUserService(repo,db);ctrl:=controller.NewUserController(svc)
    authController:=controller.NewAuthController(db);auditController:=controller.NewAuditController(db)
    studentRepo:=repository.NewStudentRepository(db);studentService:=service.NewStudentService(studentRepo,db);studentController:=controller.NewStudentController(studentService)
    academicSessionRepo:=repository.NewAcademicSessionRepository(db);termRepo:=repository.NewTermRepository(db);academicService:=service.NewAcademicService(academicSessionRepo,termRepo,db);academicController:=controller.NewAcademicController(academicService)
    classRepo:=repository.NewClassRepository(db);sectionRepo:=repository.NewSectionRepository(db);classService:=service.NewClassService(classRepo,sectionRepo,db);classController:=controller.NewClassController(classService)
    subjectRepo:=repository.NewSubjectRepository(db);subjectService:=service.NewSubjectService(subjectRepo,db);subjectController:=controller.NewSubjectController(subjectService)
    assignmentRepo:=repository.NewTeacherAssignmentRepository(db);assignmentService:=service.NewTeacherAssignmentService(assignmentRepo,db);assignmentController:=controller.NewTeacherAssignmentController(assignmentService)
    enrollmentRepo:=repository.NewEnrollmentRepository(db);enrollmentService:=service.NewEnrollmentService(enrollmentRepo,db);enrollmentController:=controller.NewEnrollmentController(enrollmentService)
    attendanceRepo:=repository.NewAttendanceRepository(db);attendanceService:=service.NewAttendanceService(attendanceRepo,db);attendanceController:=controller.NewAttendanceController(attendanceService)
    assessmentRepo:=repository.NewAssessmentRepository(db);assessmentService:=service.NewAssessmentService(assessmentRepo,db);assessmentController:=controller.NewAssessmentController(assessmentService)

    r.POST("/auth/refresh",authController.Refresh);r.POST("/auth/register",authController.Register);r.POST("/auth/login",authController.Login);r.POST("/auth/logout",authController.Logout);r.POST("/auth/forgot-password",authController.ForgotPassword);r.POST("/auth/reset-password",authController.ResetPassword)
    protected:=r.Group("/");protected.Use(middleware.AuthMiddleware(db));protected.GET("/me",ctrl.GetMe);protected.PUT("/me",ctrl.UpdateMe);protected.POST("/auth/change-password",authController.ChangePassword);protected.POST("/auth/logout-all",authController.LogoutAll);protected.GET("/sessions",authController.GetSessions);protected.DELETE("/sessions/:id",authController.RevokeSession)
    admin:=r.Group("/admin");admin.Use(middleware.AuthMiddleware(db))
    admin.GET("/roles",middleware.RequirePermission(authz.PermissionRolesAssign),authController.ListRoles)
    admin.GET("/audit-logs",middleware.RequirePermission(authz.PermissionAuditRead),auditController.List)
    admin.POST("/students",middleware.RequirePermission(authz.PermissionStudentsCreate),studentController.Create);admin.GET("/students",middleware.RequirePermission(authz.PermissionStudentsRead),studentController.List);admin.GET("/students/:id",middleware.RequirePermission(authz.PermissionStudentsRead),studentController.Get);admin.PUT("/students/:id",middleware.RequirePermission(authz.PermissionStudentsUpdate),studentController.Update);admin.DELETE("/students/:id",middleware.RequirePermission(authz.PermissionStudentsDelete),studentController.Delete)
    admin.GET("/academic-sessions",middleware.RequirePermission(authz.PermissionAcademicRead),academicController.ListSessions);admin.GET("/academic-sessions/:id",middleware.RequirePermission(authz.PermissionAcademicRead),academicController.GetSession);admin.POST("/academic-sessions",middleware.RequirePermission(authz.PermissionAcademicManage),academicController.CreateSession);admin.PUT("/academic-sessions/:id",middleware.RequirePermission(authz.PermissionAcademicManage),academicController.UpdateSession);admin.DELETE("/academic-sessions/:id",middleware.RequirePermission(authz.PermissionAcademicManage),academicController.DeleteSession);admin.GET("/academic-sessions/:sessionId/terms",middleware.RequirePermission(authz.PermissionAcademicRead),academicController.ListTerms);admin.POST("/academic-sessions/:sessionId/terms",middleware.RequirePermission(authz.PermissionAcademicManage),academicController.CreateTerm);admin.GET("/terms/:id",middleware.RequirePermission(authz.PermissionAcademicRead),academicController.GetTerm);admin.PUT("/terms/:id",middleware.RequirePermission(authz.PermissionAcademicManage),academicController.UpdateTerm);admin.DELETE("/terms/:id",middleware.RequirePermission(authz.PermissionAcademicManage),academicController.DeleteTerm)
    admin.POST("/users",middleware.RequirePermission(authz.PermissionUsersCreate),ctrl.CreateUser);admin.GET("/users",middleware.RequirePermission(authz.PermissionUsersRead),ctrl.GetUsers);admin.GET("/users/:id",middleware.RequirePermission(authz.PermissionUsersRead),ctrl.GetUser);admin.PUT("/users/:id/role",middleware.RequirePermission(authz.PermissionRolesAssign),authController.AssignRole);admin.DELETE("/users/:id",middleware.RequirePermission(authz.PermissionUsersDelete),ctrl.DeleteUser)
    admin.GET("/classes",middleware.RequirePermission(authz.PermissionClassesRead),classController.ListClasses);admin.GET("/classes/:id",middleware.RequirePermission(authz.PermissionClassesRead),classController.GetClass);admin.POST("/classes",middleware.RequirePermission(authz.PermissionClassesManage),classController.CreateClass);admin.PUT("/classes/:id",middleware.RequirePermission(authz.PermissionClassesManage),classController.UpdateClass);admin.DELETE("/classes/:id",middleware.RequirePermission(authz.PermissionClassesManage),classController.DeleteClass);admin.GET("/classes/:classId/sections",middleware.RequirePermission(authz.PermissionClassesRead),classController.ListSections);admin.POST("/classes/:classId/sections",middleware.RequirePermission(authz.PermissionClassesManage),classController.CreateSection);admin.GET("/sections/:id",middleware.RequirePermission(authz.PermissionClassesRead),classController.GetSection);admin.PUT("/sections/:id",middleware.RequirePermission(authz.PermissionClassesManage),classController.UpdateSection);admin.DELETE("/sections/:id",middleware.RequirePermission(authz.PermissionClassesManage),classController.DeleteSection)
    admin.GET("/subjects",middleware.RequirePermission(authz.PermissionSubjectsRead),subjectController.List);admin.GET("/subjects/:id",middleware.RequirePermission(authz.PermissionSubjectsRead),subjectController.Get);admin.POST("/subjects",middleware.RequirePermission(authz.PermissionSubjectsManage),subjectController.Create);admin.PUT("/subjects/:id",middleware.RequirePermission(authz.PermissionSubjectsManage),subjectController.Update);admin.DELETE("/subjects/:id",middleware.RequirePermission(authz.PermissionSubjectsManage),subjectController.Delete)
    admin.GET("/teacher-assignments",middleware.RequirePermission(authz.PermissionAssignmentsRead),assignmentController.List);admin.GET("/teacher-assignments/:id",middleware.RequirePermission(authz.PermissionAssignmentsRead),assignmentController.Get);admin.POST("/teacher-assignments",middleware.RequirePermission(authz.PermissionAssignmentsManage),assignmentController.Create);admin.PUT("/teacher-assignments/:id",middleware.RequirePermission(authz.PermissionAssignmentsManage),assignmentController.Update);admin.DELETE("/teacher-assignments/:id",middleware.RequirePermission(authz.PermissionAssignmentsManage),assignmentController.Delete)
    admin.GET("/enrollments",middleware.RequirePermission(authz.PermissionEnrollmentRead),enrollmentController.List);admin.GET("/enrollments/:id",middleware.RequirePermission(authz.PermissionEnrollmentRead),enrollmentController.Get);admin.POST("/enrollments",middleware.RequirePermission(authz.PermissionEnrollmentManage),enrollmentController.Create);admin.PUT("/enrollments/:id",middleware.RequirePermission(authz.PermissionEnrollmentManage),enrollmentController.Update);admin.DELETE("/enrollments/:id",middleware.RequirePermission(authz.PermissionEnrollmentManage),enrollmentController.Delete)
    admin.GET("/attendance",middleware.RequirePermission(authz.PermissionAttendanceRead),attendanceController.List);admin.GET("/attendance/:id",middleware.RequirePermission(authz.PermissionAttendanceRead),attendanceController.Get);admin.POST("/attendance",middleware.RequirePermission(authz.PermissionAttendanceManage),attendanceController.Create);admin.PUT("/attendance/:id",middleware.RequirePermission(authz.PermissionAttendanceManage),attendanceController.Update);admin.DELETE("/attendance/:id",middleware.RequirePermission(authz.PermissionAttendanceManage),attendanceController.Delete)
    admin.GET("/assessments",middleware.RequirePermission(authz.PermissionAssessmentsRead),assessmentController.List);admin.GET("/assessments/:id",middleware.RequirePermission(authz.PermissionAssessmentsRead),assessmentController.Get);admin.POST("/assessments",middleware.RequirePermission(authz.PermissionAssessmentsManage),assessmentController.Create);admin.PUT("/assessments/:id",middleware.RequirePermission(authz.PermissionAssessmentsManage),assessmentController.Update);admin.DELETE("/assessments/:id",middleware.RequirePermission(authz.PermissionAssessmentsManage),assessmentController.Delete)
    admin.POST("/users/:id/activate",middleware.RequirePermission(authz.PermissionUsersActivate),authController.ActivateUser);admin.POST("/users/:id/deactivate",middleware.RequirePermission(authz.PermissionUsersDeactivate),authController.DeactivateUser)
    port:=os.Getenv("APP_PORT");if port==""{port="8080"};log.Println("Server running on :"+port);if err:=r.Run(":"+port);err!=nil{log.Fatal(err)}
}
