package main

import (
    "log"
    "os"
    "github.com/onoja217/users-management-app/internal/server"
    "github.com/gin-gonic/gin"
    "github.com/onoja217/users-management-app/internal/auth"
    "github.com/onoja217/users-management-app/internal/authz"
    "github.com/onoja217/users-management-app/internal/bootstrap"
    "github.com/onoja217/users-management-app/internal/controller"
    "github.com/onoja217/users-management-app/internal/database"
    "github.com/onoja217/users-management-app/internal/middleware"
    "github.com/onoja217/users-management-app/internal/repository"
    "github.com/onoja217/users-management-app/internal/service"
)
func main() {
    if err:=server.ValidateEnvironment();err!=nil{log.Fatal(err)}
    if err:=auth.ConfigureSecret(os.Getenv("JWT_SECRET"));err!=nil{log.Fatal(err)}
    db,err:=database.Connect();if err!=nil{log.Fatal(err)}
    if err:=database.Migrate(db);err!=nil{log.Fatal(err)}
    if err:=bootstrap.EnsureInitialAdmin(db);err!=nil{log.Fatal(err)}
    r:=gin.Default();r.SetTrustedProxies(nil);server.Configure(r)
    repo:=repository.NewUserRepository(db);svc:=service.NewUserService(repo,db);ctrl:=controller.NewUserController(svc)
    authController:=controller.NewAuthController(db);auditController:=controller.NewAuditController(db);platformSchoolController:=controller.NewPlatformSchoolController(db)
    studentRepo:=repository.NewStudentRepository(db);studentService:=service.NewStudentService(studentRepo,db);studentController:=controller.NewStudentController(studentService)
     schoolRepo:=repository.NewSchoolRepository(db);schoolService:=service.NewSchoolService(schoolRepo,db);schoolController:=controller.NewSchoolController(schoolService)
    academicSessionRepo:=repository.NewAcademicSessionRepository(db);termRepo:=repository.NewTermRepository(db);academicService:=service.NewAcademicService(academicSessionRepo,termRepo,db);academicController:=controller.NewAcademicController(academicService);academicReadinessService:=service.NewAcademicReadinessService(db);academicReadinessController:=controller.NewAcademicReadinessController(academicReadinessService)
    classRepo:=repository.NewClassRepository(db);sectionRepo:=repository.NewSectionRepository(db);classService:=service.NewClassService(classRepo,sectionRepo,db);classController:=controller.NewClassController(classService)
    subjectRepo:=repository.NewSubjectRepository(db);subjectService:=service.NewSubjectService(subjectRepo,db);subjectController:=controller.NewSubjectController(subjectService)
    assignmentRepo:=repository.NewTeacherAssignmentRepository(db);assignmentService:=service.NewTeacherAssignmentService(assignmentRepo,db);assignmentController:=controller.NewTeacherAssignmentController(assignmentService)
    enrollmentRepo:=repository.NewEnrollmentRepository(db);enrollmentService:=service.NewEnrollmentService(enrollmentRepo,db);enrollmentController:=controller.NewEnrollmentController(enrollmentService)
    attendanceRepo:=repository.NewAttendanceRepository(db);attendanceService:=service.NewAttendanceService(attendanceRepo,db);attendanceController:=controller.NewAttendanceController(attendanceService)
    assessmentRepo:=repository.NewAssessmentRepository(db);assessmentService:=service.NewAssessmentService(assessmentRepo,db);assessmentController:=controller.NewAssessmentController(assessmentService)
    resultRepo:=repository.NewAssessmentResultRepository(db);resultService:=service.NewAssessmentResultService(resultRepo,db);resultController:=controller.NewAssessmentResultController(resultService)
    feeRepo:=repository.NewFeeItemRepository(db);invoiceRepo:=repository.NewInvoiceRepository(db);paymentRepo:=repository.NewPaymentRepository(db);financeService:=service.NewFinanceService(feeRepo,invoiceRepo,paymentRepo,db);financeController:=controller.NewFinanceController(financeService)
    timetableRepo:=repository.NewTimetableRepository(db);timetableService:=service.NewTimetableService(timetableRepo,db);timetableController:=controller.NewTimetableController(timetableService)
    guardianRepo:=repository.NewGuardianRepository(db);guardianService:=service.NewGuardianService(guardianRepo,db);guardianController:=controller.NewGuardianController(guardianService);personOnboardingService:=service.NewPersonOnboardingService(db);personOnboardingController:=controller.NewPersonOnboardingController(personOnboardingService)
    notificationRepo:=repository.NewNotificationRepository(db);notificationService:=service.NewNotificationService(notificationRepo,db);notificationController:=controller.NewNotificationController(notificationService);bulkImportService:=service.NewBulkImportService(db);bulkImportService.ResumePending();bulkImportController:=controller.NewBulkImportController(bulkImportService);studentPortalService:=service.NewStudentPortalService(db);studentPortalController:=controller.NewStudentPortalController(studentPortalService)

    r.GET("/platform/schools",middleware.AuthMiddleware(db),middleware.RequireRole(authz.RoleSuperAdmin),platformSchoolController.List);r.GET("/platform/monitoring",middleware.AuthMiddleware(db),middleware.RequireRole(authz.RoleSuperAdmin),platformSchoolController.Monitoring);r.POST("/platform/schools",middleware.AuthMiddleware(db),middleware.RequireRole(authz.RoleSuperAdmin),platformSchoolController.Create);r.PUT("/platform/schools/:id",middleware.AuthMiddleware(db),middleware.RequireRole(authz.RoleSuperAdmin),platformSchoolController.Update);r.POST("/auth/school-signup",authController.SchoolSignup);r.POST("/auth/refresh",authController.Refresh);r.POST("/auth/login",authController.Login);r.POST("/auth/logout",authController.Logout);r.POST("/auth/forgot-password",authController.ForgotPassword);r.POST("/auth/reset-password",authController.ResetPassword)
    profile:=r.Group("/")
    profile.Use(middleware.AuthMiddleware(db))
    profile.GET("/me",ctrl.GetMe)
    profile.PUT("/me",ctrl.UpdateMe)
    protected:=r.Group("/");protected.Use(middleware.AuthMiddleware(db));protected.Use(middleware.RequireSchoolContext(db));protected.GET("/teacher/enrollments",middleware.RequirePermission(authz.PermissionTeacherWorkspaceRead),middleware.RequireRole(authz.RoleTeacher),enrollmentController.TeacherList);protected.GET("/teacher/assignments",middleware.RequirePermission(authz.PermissionTeacherWorkspaceRead),middleware.RequireRole(authz.RoleTeacher),assignmentController.TeacherList);protected.GET("/teacher/attendance",middleware.RequirePermission(authz.PermissionAttendanceRead),middleware.RequireRole(authz.RoleTeacher),attendanceController.TeacherList);protected.POST("/teacher/attendance",middleware.RequirePermission(authz.PermissionAttendanceManage),middleware.RequireRole(authz.RoleTeacher),attendanceController.TeacherCreate);protected.GET("/teacher/assessments",middleware.RequirePermission(authz.PermissionAssessmentsRead),middleware.RequireRole(authz.RoleTeacher),assessmentController.TeacherList);protected.POST("/teacher/assessments",middleware.RequirePermission(authz.PermissionAssessmentsManage),middleware.RequireRole(authz.RoleTeacher),assessmentController.TeacherCreate);protected.GET("/teacher/results",middleware.RequirePermission(authz.PermissionResultsRead),middleware.RequireRole(authz.RoleTeacher),resultController.TeacherList);protected.POST("/teacher/results",middleware.RequirePermission(authz.PermissionResultsManage),middleware.RequireRole(authz.RoleTeacher),resultController.TeacherCreate);protected.GET("/teacher/timetable",middleware.RequirePermission(authz.PermissionTimetableRead),timetableController.TeacherView);protected.POST("/auth/change-password",authController.ChangePassword);protected.POST("/auth/logout-all",authController.LogoutAll);protected.GET("/sessions",authController.GetSessions);protected.DELETE("/sessions/:id",authController.RevokeSession)
    authenticated:=r.Group("");authenticated.Use(middleware.AuthMiddleware(db));authenticated.Use(middleware.RequireSchoolContext(db));authenticated.GET("/academic-context",middleware.RequirePermission(authz.PermissionAcademicRead),academicController.GetContext)
    admin:=r.Group("/admin");admin.Use(middleware.AuthMiddleware(db));admin.Use(middleware.RequireSchoolContext(db))
    admin.GET("/school",middleware.RequireRole(authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionSchoolRead),schoolController.Get);admin.PUT("/school",middleware.RequireRole(authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionSchoolManage),schoolController.Update);admin.GET("/roles",middleware.RequirePermission(authz.PermissionRolesAssign),authController.ListRoles);admin.GET("/audit-logs",middleware.RequirePermission(authz.PermissionAuditRead),auditController.List)
    admin.POST("/students",middleware.RequirePermission(authz.PermissionStudentsCreate),studentController.Create);admin.GET("/students",middleware.RequirePermission(authz.PermissionStudentsRead),studentController.List);admin.GET("/students/:id",middleware.RequirePermission(authz.PermissionStudentsRead),studentController.Get);admin.PUT("/students/:id",middleware.RequirePermission(authz.PermissionStudentsUpdate),studentController.Update);admin.DELETE("/students/:id",middleware.RequirePermission(authz.PermissionStudentsDelete),studentController.Delete)
    admin.GET("/school/readiness",middleware.RequirePermission(authz.PermissionAcademicRead),academicReadinessController.Get);admin.GET("/academic-sessions",middleware.RequirePermission(authz.PermissionAcademicRead),academicController.ListSessions);admin.GET("/academic-sessions/:id/terms",middleware.RequirePermission(authz.PermissionAcademicRead),academicController.ListTerms);admin.POST("/academic-sessions/:id/terms",middleware.RequirePermission(authz.PermissionAcademicManage),academicController.CreateTerm);admin.GET("/academic-sessions/:id",middleware.RequirePermission(authz.PermissionAcademicRead),academicController.GetSession);admin.POST("/academic-sessions",middleware.RequirePermission(authz.PermissionAcademicManage),academicController.CreateSession);admin.PUT("/academic-sessions/:id",middleware.RequirePermission(authz.PermissionAcademicManage),academicController.UpdateSession);admin.DELETE("/academic-sessions/:id",middleware.RequirePermission(authz.PermissionAcademicManage),academicController.DeleteSession);admin.GET("/terms/:id",middleware.RequirePermission(authz.PermissionAcademicRead),academicController.GetTerm);admin.PUT("/terms/:id",middleware.RequirePermission(authz.PermissionAcademicManage),academicController.UpdateTerm);admin.DELETE("/terms/:id",middleware.RequirePermission(authz.PermissionAcademicManage),academicController.DeleteTerm)
    admin.POST("/users",middleware.RequirePermission(authz.PermissionUsersCreate),ctrl.CreateUser);admin.POST("/onboarding/people",middleware.RequireRole(authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionUsersCreate),personOnboardingController.Create);admin.POST("/onboarding/bulk/preview",middleware.RequireRole(authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionUsersCreate),bulkImportController.Create);admin.POST("/onboarding/bulk/:id/start",middleware.RequireRole(authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionUsersCreate),bulkImportController.Start);admin.GET("/onboarding/bulk",middleware.RequireRole(authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionUsersRead),bulkImportController.List);admin.GET("/onboarding/bulk/:id",middleware.RequireRole(authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionUsersRead),bulkImportController.Get);admin.GET("/users",middleware.RequirePermission(authz.PermissionUsersRead),ctrl.GetUsers);admin.GET("/users/:id",middleware.RequirePermission(authz.PermissionUsersRead),ctrl.GetUser);admin.PUT("/users/:id/role",middleware.RequirePermission(authz.PermissionRolesAssign),authController.AssignRole);admin.DELETE("/users/:id",middleware.RequirePermission(authz.PermissionUsersDelete),ctrl.DeleteUser)
    admin.GET("/classes",middleware.RequirePermission(authz.PermissionClassesRead),classController.ListClasses);admin.GET("/classes/:id",middleware.RequirePermission(authz.PermissionClassesRead),classController.GetClass);admin.POST("/classes",middleware.RequirePermission(authz.PermissionClassesManage),classController.CreateClass);admin.PUT("/classes/:id",middleware.RequirePermission(authz.PermissionClassesManage),classController.UpdateClass);admin.DELETE("/classes/:id",middleware.RequirePermission(authz.PermissionClassesManage),classController.DeleteClass);admin.GET("/classes/:id/sections",middleware.RequirePermission(authz.PermissionClassesRead),classController.ListSections);admin.POST("/classes/:id/sections",middleware.RequirePermission(authz.PermissionClassesManage),classController.CreateSection);admin.GET("/sections/:id",middleware.RequirePermission(authz.PermissionClassesRead),classController.GetSection);admin.PUT("/sections/:id",middleware.RequirePermission(authz.PermissionClassesManage),classController.UpdateSection);admin.DELETE("/sections/:id",middleware.RequirePermission(authz.PermissionClassesManage),classController.DeleteSection)
    admin.GET("/subjects",middleware.RequirePermission(authz.PermissionSubjectsRead),subjectController.List);admin.GET("/subjects/:id",middleware.RequirePermission(authz.PermissionSubjectsRead),subjectController.Get);admin.POST("/subjects",middleware.RequirePermission(authz.PermissionSubjectsManage),subjectController.Create);admin.PUT("/subjects/:id",middleware.RequirePermission(authz.PermissionSubjectsManage),subjectController.Update);admin.DELETE("/subjects/:id",middleware.RequirePermission(authz.PermissionSubjectsManage),subjectController.Delete)
    admin.GET("/teacher-assignments",middleware.RequirePermission(authz.PermissionAssignmentsRead),assignmentController.List);admin.GET("/teacher-assignments/coverage",middleware.RequirePermission(authz.PermissionAssignmentsRead),assignmentController.Coverage);admin.GET("/teacher-assignments/:id",middleware.RequirePermission(authz.PermissionAssignmentsRead),assignmentController.Get);admin.POST("/teacher-assignments",middleware.RequirePermission(authz.PermissionAssignmentsManage),assignmentController.Create);admin.PUT("/teacher-assignments/:id",middleware.RequirePermission(authz.PermissionAssignmentsManage),assignmentController.Update);admin.DELETE("/teacher-assignments/:id",middleware.RequirePermission(authz.PermissionAssignmentsManage),assignmentController.Delete)
    admin.GET("/enrollments",middleware.RequirePermission(authz.PermissionEnrollmentRead),enrollmentController.List);admin.GET("/enrollments/student/:studentId",middleware.RequirePermission(authz.PermissionEnrollmentRead),enrollmentController.History);admin.GET("/enrollments/:id",middleware.RequirePermission(authz.PermissionEnrollmentRead),enrollmentController.Get);admin.POST("/enrollments",middleware.RequirePermission(authz.PermissionEnrollmentManage),enrollmentController.Create);admin.POST("/enrollments/:id/place",middleware.RequirePermission(authz.PermissionEnrollmentManage),enrollmentController.Place);admin.PUT("/enrollments/:id",middleware.RequirePermission(authz.PermissionEnrollmentManage),enrollmentController.Update);admin.DELETE("/enrollments/:id",middleware.RequirePermission(authz.PermissionEnrollmentManage),enrollmentController.Delete)
    admin.GET("/attendance",middleware.RequireRole(authz.RoleSuperAdmin,authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionAttendanceRead),attendanceController.List);admin.GET("/attendance/:id",middleware.RequireRole(authz.RoleSuperAdmin,authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionAttendanceRead),attendanceController.Get);admin.POST("/attendance",middleware.RequireRole(authz.RoleSuperAdmin,authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionAttendanceManage),attendanceController.Create);admin.PUT("/attendance/:id",middleware.RequireRole(authz.RoleSuperAdmin,authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionAttendanceManage),attendanceController.Update);admin.DELETE("/attendance/:id",middleware.RequirePermission(authz.PermissionAttendanceManage),attendanceController.Delete)
    admin.GET("/assessments",middleware.RequireRole(authz.RoleSuperAdmin,authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionAssessmentsRead),assessmentController.List);admin.GET("/assessments/:id",middleware.RequirePermission(authz.PermissionAssessmentsRead),assessmentController.Get);admin.POST("/assessments",middleware.RequirePermission(authz.PermissionAssessmentsManage),assessmentController.Create);admin.PUT("/assessments/:id",middleware.RequirePermission(authz.PermissionAssessmentsManage),assessmentController.Update);admin.DELETE("/assessments/:id",middleware.RequirePermission(authz.PermissionAssessmentsManage),assessmentController.Delete)
    admin.GET("/assessment-results",middleware.RequireRole(authz.RoleSuperAdmin,authz.RoleSchoolAdmin),middleware.RequirePermission(authz.PermissionResultsRead),resultController.List);admin.GET("/assessment-results/:id",middleware.RequirePermission(authz.PermissionResultsRead),resultController.Get);admin.POST("/assessment-results",middleware.RequirePermission(authz.PermissionResultsManage),resultController.Create);admin.PUT("/assessment-results/:id",middleware.RequirePermission(authz.PermissionResultsManage),resultController.Update);admin.DELETE("/assessment-results/:id",middleware.RequirePermission(authz.PermissionResultsManage),resultController.Delete);admin.GET("/report-cards/:enrollmentId",middleware.RequirePermission(authz.PermissionResultsRead),resultController.ReportCard)
    admin.GET("/fees",middleware.RequirePermission(authz.PermissionFeesRead),financeController.ListFees);admin.GET("/fees/:id",middleware.RequirePermission(authz.PermissionFeesRead),financeController.GetFee);admin.POST("/terms/:id/fees",middleware.RequirePermission(authz.PermissionFeesManage),financeController.CreateFee);admin.PUT("/fees/:id",middleware.RequirePermission(authz.PermissionFeesManage),financeController.UpdateFee);admin.DELETE("/fees/:id",middleware.RequirePermission(authz.PermissionFeesManage),financeController.DeleteFee)
    admin.GET("/invoices",middleware.RequirePermission(authz.PermissionInvoicesRead),financeController.ListInvoices);admin.GET("/invoices/:id",middleware.RequirePermission(authz.PermissionInvoicesRead),financeController.GetInvoice);admin.POST("/invoices",middleware.RequirePermission(authz.PermissionInvoicesManage),financeController.CreateInvoice);admin.GET("/invoices/:id/payments",middleware.RequirePermission(authz.PermissionPaymentsRead),financeController.ListPayments);admin.POST("/invoices/:id/payments",middleware.RequirePermission(authz.PermissionPaymentsManage),financeController.CreatePayment)
    admin.GET("/timetable",middleware.RequirePermission(authz.PermissionTimetableRead),timetableController.List);admin.GET("/timetable/:id",middleware.RequirePermission(authz.PermissionTimetableRead),timetableController.Get);admin.POST("/timetable",middleware.RequirePermission(authz.PermissionTimetableManage),timetableController.Create);admin.PUT("/timetable/:id",middleware.RequirePermission(authz.PermissionTimetableManage),timetableController.Update);admin.DELETE("/timetable/:id",middleware.RequirePermission(authz.PermissionTimetableManage),timetableController.Delete)
    admin.GET("/announcements",middleware.RequirePermission(authz.PermissionNotificationsRead),notificationController.Announcements);admin.POST("/announcements",middleware.RequirePermission(authz.PermissionNotificationsManage),notificationController.CreateAnnouncement);admin.POST("/announcements/:id/publish",middleware.RequirePermission(authz.PermissionNotificationsManage),notificationController.Publish);admin.POST("/guardian-links",middleware.RequirePermission(authz.PermissionParentPortalManage),guardianController.CreateLink)
    student:=r.Group("/student");student.Use(middleware.AuthMiddleware(db));student.Use(middleware.RequireSchoolContext(db));student.Use(middleware.RequirePermission(authz.PermissionStudentPortalRead));student.GET("/profile",studentPortalController.Profile);student.GET("/enrollment",studentPortalController.Enrollment);student.GET("/terms",studentPortalController.Terms);student.GET("/attendance",studentPortalController.Attendance);student.GET("/timetable",studentPortalController.Timetable);student.GET("/report-cards/:termId",studentPortalController.ReportCard);student.GET("/invoices",studentPortalController.Invoices);student.GET("/payments",studentPortalController.Payments)
    parent:=r.Group("/parent");parent.Use(middleware.AuthMiddleware(db));parent.Use(middleware.RequireSchoolContext(db));parent.Use(middleware.RequirePermission(authz.PermissionParentPortalRead));protected.GET("/notifications",middleware.RequirePermission(authz.PermissionNotificationsRead),notificationController.Mine);protected.POST("/notifications/:id/read",middleware.RequirePermission(authz.PermissionNotificationsRead),notificationController.Read)
    parent.GET("/terms",guardianController.Terms);parent.GET("/children",guardianController.Children);parent.GET("/children/:studentId/attendance",guardianController.Attendance);parent.GET("/children/:studentId/report-cards/:termId",guardianController.ReportCard);parent.GET("/children/:studentId/timetable",guardianController.Timetable);parent.GET("/children/:studentId/invoices",guardianController.Invoices);parent.GET("/children/:studentId/payments",guardianController.Payments)
    admin.POST("/users/:id/activate",middleware.RequirePermission(authz.PermissionUsersActivate),authController.ActivateUser);admin.POST("/users/:id/deactivate",middleware.RequirePermission(authz.PermissionUsersDeactivate),authController.DeactivateUser)
    port:=os.Getenv("PORT");if port==""{port=os.Getenv("APP_PORT")};if port==""{port="8080"};if err:=server.Start(r,port);err!=nil{log.Fatal(err)}
}